microsoft/component-detection

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Assignees field can't be empty.
=> Fix feature request template

src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetector.cs
Minor formatting changes and Fixed log interpolation in NpmComponentDetector.
=> Minor fixes in NpmComponentDetector.

src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs, src/Microsoft.ComponentDetection.Detectors/nuget/NuGetComponentDetector.cs, src/Microsoft.ComponentDetection.Detectors/poetry/Contracts/PoetryLock.cs, src/Microsoft.ComponentDetection.Detectors/poetry/Contracts/PoetryPackage.cs, src/Microsoft.ComponentDetection.Detectors/poetry/Contracts/PoetrySource.cs, src/Microsoft.ComponentDetection.Detectors/poetry/PoetryComponentDetector.cs, src/Microsoft.ComponentDetection/LoaderInteropConstants.cs, src/Microsoft.ComponentDetection/Program.cs, test/Microsoft.ComponentDetection.Detectors.Tests/GoComponentDetectorTests.cs, test/Microsoft.ComponentDetection.Detectors.Tests/NpmDetectorTests.cs, test/Microsoft.ComponentDetection.Detectors.Tests/NugetTestUtilities.cs, test/Microsoft.ComponentDetection.Orchestrator.Tests/GraphTranslationUtilityTests.cs, test/Microsoft.ComponentDetection.TestsUtilities/EnumerableStringComparer.cs
Build warning automatically fixed by IDE
=> refactor: remove unused usings

.github/workflows/release.yml
See https://github.com/NuGet/Home/issues/7792
=> ci: azure devops requires a source to be configured

test/Microsoft.ComponentDetection.Detectors.Tests/Microsoft.ComponentDetection.Detectors.Tests.csproj, test/Microsoft.ComponentDetection.Detectors.Tests/VcpkgComponentDetectorTests.cs
=> Fix Vcpkg test

src/Microsoft.ComponentDetection.Contracts/TypedComponent/SpdxComponent.cs, src/Microsoft.ComponentDetection.Detectors/spdx/Spdx22ComponentDetector.cs, test/Microsoft.ComponentDetection.Detectors.Tests/SPDX22ComponentDetectorTests.cs
Adding Path field to SPDX detector for SBOM generation.
=> Add Path field to SPDX Detector

docs/update-syft.md
This was an action item out of our last community meeting: https://github.com/microsoft/component-detection/discussions/134
=> docs: how to update syft

.editorconfig, src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs, src/Microsoft.ComponentDetection.Detectors/linux/LinuxContainerDetector.cs
Single line comment should begin with a space
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1005.md
=> refactor: fix SA1005

.editorconfig, test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/BcdeScanExecutionServiceTests.cs
=> refactor: fix SA1137

.editorconfig, test/Microsoft.ComponentDetection.Detectors.Tests/NuGetComponentDetectorTests.cs
=> Refactor: fix SA1011

.editorconfig, src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs
=> Refactor: Fix SA1008

.editorconfig, src/Microsoft.ComponentDetection.Orchestrator/ArgumentSets/BcdeArguments.cs, test/Microsoft.ComponentDetection.Detectors.Tests/LinuxContainerDetectorTests.cs, test/Microsoft.ComponentDetection.Detectors.Tests/NuGetComponentDetectorTests.cs
=> Refactor: Fix SA1012, SA1013, SA1026 and SA1118

.editorconfig, src/Microsoft.ComponentDetection.Common/DockerService.cs, src/Microsoft.ComponentDetection.Common/FastDirectoryWalkerFactory.cs, src/Microsoft.ComponentDetection.Common/SafeFileEnumerable.cs, src/Microsoft.ComponentDetection.Contracts/BcdeModels/TypedComponentConverter.cs, src/Microsoft.ComponentDetection.Contracts/IDockerService.cs, src/Microsoft.ComponentDetection.Contracts/TypedComponent/SpdxComponent.cs, src/Microsoft.ComponentDetection.Detectors/linux/LinuxContainerDetector.cs, src/Microsoft.ComponentDetection.Detectors/maven/MvnCliComponentDetector.cs, src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetectorWithRoots.cs, src/Microsoft.ComponentDetection.Detectors/rust/SemVer/Desugarer.cs, src/Microsoft.ComponentDetection.Orchestrator/Orchestrator.cs, test/Microsoft.ComponentDetection.Common.Tests/ComponentStreamEnumerableTests.cs, test/Microsoft.ComponentDetection.Common.Tests/FileEnumerationTests.cs, test/Microsoft.ComponentDetection.Detectors.Tests/LinuxContainerDetectorTests.cs, test/Microsoft.ComponentDetection.Detectors.Tests/NpmDetectorWithRootsTests.cs, test/Microsoft.ComponentDetection.Detectors.Tests/NpmUtilitiesTests.cs, test/Microsoft.ComponentDetection.Detectors.Tests/PnpmDetectorTests.cs, test/Microsoft.ComponentDetection.Detectors.Tests/PodDetectorTest.cs, test/Microsoft.ComponentDetection.Detectors.Tests/PoetryComponentDetectorTests.cs, test/Microsoft.ComponentDetection.Detectors.Tests/RubyDetectorTest.cs, test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/BcdeScanExecutionServiceTests.cs, test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DetectorProcessingServiceTests.cs
=> Refactor: Fix SA1117

.editorconfig, src/Microsoft.ComponentDetection.Common/DependencyScopeComparer.cs, src/Microsoft.ComponentDetection.Common/DockerService.cs, src/Microsoft.ComponentDetection.Detectors/dockerfile/DockerfileComponentDetector.cs, src/Microsoft.ComponentDetection.Detectors/linux/LinuxContainerDetector.cs, src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorRestrictionService.cs, test/Microsoft.ComponentDetection.Detectors.Tests/LinuxContainerDetectorTests.cs, test/Microsoft.ComponentDetection.Detectors.Tests/NpmTestUtilities.cs, test/Microsoft.ComponentDetection.Detectors.Tests/PipResolverTests.cs, test/Microsoft.ComponentDetection.Detectors.Tests/YarnParserTests.cs, test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/BcdeScanExecutionServiceTests.cs, test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DetectorListingCommandServiceTests.cs, test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DetectorProcessingServiceTests.cs, test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DetectorRestrictionServiceTests.cs
Braces for multi-line statements should not share line https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1500.md
=> refactor: fix SA1500

.github/workflows/codeql-analysis.yml
=> ci: fix codeql workflow

src/Microsoft.ComponentDetection/Program.cs
=> refactor: use asynchronous main method

src/Microsoft.ComponentDetection.Detectors/pip/IPyPiClient.cs
Looked at the documentation and changed the wording in the suppression message a little to match.
=> Changed the suppression messaged according to documentation for 1202

Directory.Build.props
Updated as per https://aka.ms/Microsoft-NuGet-Compliance
=> docs: fix copyright text

docs/running-verification-tests.md, test/Microsoft.ComponentDetection.VerificationTests/resources/VerificationTest.ps1
Automation script for running the verification test locally. 
This script mimics github action [snapshot-verify.yml](https://github.com/microsoft/component-detection/blob/main/.github/workflows/snapshot-verify.yml) to execute verification tests.
=> Added script for running verification test locally

.editorconfig
Add IDE0052 to warning exclusion which will be addressed as part of #202
=> Add IDE0052 to warning exclusion

src/Microsoft.ComponentDetection.Detectors/nuget/NuGetPackagesConfigDetector.cs, test/Microsoft.ComponentDetection.VerificationTests/resources/nuget/packages-config/packages.config
=> fix: catch `PackagesConfigReaderException` in `NuGetPackagesConfigDetector`

.github/workflows/snapshot-publish.yml, .github/workflows/snapshot-verify.yml
=> ci: fix ivy install

.git-blame-ignore-revs
- https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/
- https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
=> chore: ignore file scope namespaces commit in `git blame`

src/Microsoft.ComponentDetection.Common/PathUtilityService.cs, test/Microsoft.ComponentDetection.Common.Tests/SafeFileEnumerableTests.cs
=> refactor: simplify `PathUtilityService`

docs/update-syft.md, src/Microsoft.ComponentDetection.Detectors/linux/Contracts/SyftOutput.cs, src/Microsoft.ComponentDetection.Detectors/linux/LinuxScanner.cs
Updates syft to version v0.74.0. We also now push the proper manifest and all images to ACR (thanks @JamieMagee), so scanning on ARM now works.
Fixes #467
=> feat: update syft to v0.74.0 & add support for Docker scanning on ARM

Directory.Packages.props, src/Microsoft.ComponentDetection.Detectors/Microsoft.ComponentDetection.Detectors.csproj
=> chore: use `Tomlyn.Signed`

.github/workflows/ossf-scorecard.yml
See https://github.com/ossf/scorecard-action
=> ci: add ossf scorecard scanning

.github/workflows/detector-version-bump-reminder.yml
=> fix(ci): add PR write perm

renovate.json
=> chore: pin GitHub actions

src/Microsoft.ComponentDetection.Orchestrator/Experiments/Models/ExperimentDiff.cs
This is needed for JSON deserialization. Also updated the xml docs to follow the "standard" text.+
=> fix(experiments): add ctor to `ExperimentDiff`

docs/detectors/README.md, docs/detectors/nuget.md
Added doc describing NuGet Detector
=> Added NuGet Detector Doc

test/Microsoft.ComponentDetection.VerificationTests/ComponentDetectionIntegrationTests.cs
=> tests: check locations found at

README.md
Helpful to advertise in the meeting.
=> docs(readme): add community meeting info

docs/environment-variables.md, src/Microsoft.ComponentDetection.Orchestrator/Experiments/DetectorExperiments.cs, src/Microsoft.ComponentDetection.Orchestrator/Experiments/ExperimentService.cs, test/Microsoft.ComponentDetection.Orchestrator.Tests/Experiments/ExperimentServiceTests.cs
=> feat: disable detector experiments by default

src/Microsoft.ComponentDetection.Detectors/pip/SimplePythonResolver.cs
Make the regex a static compiled regex, and cleanup some of the code.
=> refactor(pip): make regex static & cleanup resolver

src/Microsoft.ComponentDetection.Detectors/pip/SimplePythonResolver.cs
Achieves decent performance gains (25%!). Benchmarked with [`hyperfine`](https://github.com/sharkdp/hyperfine)
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `main` | 10.594 ± 4.735 | 5.115 | 17.982 | 1.25 ± 0.70 |
| `parallel-pip` | 8.456 ± 2.792 | 5.438 | 13.066 | 1.00 |
Fixes #702
=> feat(pip): fetch roots in parallel

.github/workflows/build.yml, Directory.Packages.props, test/Microsoft.ComponentDetection.Common.Tests/Microsoft.ComponentDetection.Common.Tests.csproj, test/Microsoft.ComponentDetection.Contracts.Tests/Microsoft.ComponentDetection.Contracts.Tests.csproj, test/Microsoft.ComponentDetection.Detectors.Tests/Microsoft.ComponentDetection.Detectors.Tests.csproj, test/Microsoft.ComponentDetection.Orchestrator.Tests/Microsoft.ComponentDetection.Orchestrator.Tests.csproj
=> ci: add Codecov

test/Microsoft.ComponentDetection.Common.Tests/AsyncExceptionTests.cs, test/Microsoft.ComponentDetection.Common.Tests/DockerReferenceUtilityTests.cs, test/Microsoft.ComponentDetection.Common.Tests/LazyComponentStreamTests.cs, test/Microsoft.ComponentDetection.Common.Tests/PatternMatchingUtilityTests.cs, test/Microsoft.ComponentDetection.Common.Tests/TabularStringFormatTests.cs
Adds tests to the common library to increase our testing coverage. Did not discover any bugs.
=> tests(common): add more tests

docs/detectors/go.md
Update documentation to include the relevant changes from #751
=> docs(go): add 1.17 info

test/Microsoft.ComponentDetection.VerificationTests/ComponentDetectionIntegrationTests.cs, test/Microsoft.ComponentDetection.VerificationTests/Microsoft.ComponentDetection.VerificationTests.csproj
Fixed broken verification tests from #766
=> fix(test): duplicate spdx external refs

src/Microsoft.ComponentDetection.Detectors/pip/SimplePipComponentDetector.cs
Removed simplepip from defaultoff
=> Removed simplepip from defaultoff

Directory.Packages.props
Resolving security alert that impacts some .NET environments, see https://github.com/NuGet/NuGet.Client/security/advisories/GHSA-68w7-72jg-6qpp
=> Resolve vulnerabilities in transitive dep

src/Microsoft.ComponentDetection.Orchestrator/Experiments/Configs/VcpkgExperiment.cs, src/Microsoft.ComponentDetection.Orchestrator/Extensions/ServiceCollectionExtensions.cs
Title is self-descriptive. Detector is in experimental stage, we would like to capture more insights about it.
=> Add new VCPKG experiment

src/Microsoft.ComponentDetection.Orchestrator/Extensions/ServiceCollectionExtensions.cs
Adding the go with replace experiment
=> Adding go with replace experiment

src/Microsoft.ComponentDetection.Detectors/pip/PipComponentDetector.cs
bump version since we are removing results from the detection with https://github.com/microsoft/component-detection/pull/973
=> Bump pip detector version

src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs
support for timeouts lower than 5 sec
=> Fix timeout lower bound

.azdo/release.yaml
Initial attempt to add a pipeline that pushes to the azure artifact feed upon a new github release being generated
=> Add ADO package release pipeline

docs/update-syft.md, src/Microsoft.ComponentDetection.Detectors/linux/Contracts/SyftOutput.cs, src/Microsoft.ComponentDetection.Detectors/linux/LinuxContainerDetector.cs, src/Microsoft.ComponentDetection.Detectors/linux/LinuxScanner.cs
Reverting so that some later changes (with lower risk) can be released separately. Will re-introduce later on
=> Revert "Update syft image and doc - use docker commands"

src/Microsoft.ComponentDetection.Orchestrator/Commands/ScanSettings.cs
@grvillic this is what I needed to make DetectorsFilter  work..  Without this the value I passed was ignored.
=> Fix DetectorsFilter parameter

src/Microsoft.ComponentDetection.Detectors/dotnet/DotNetComponentDetector.cs, src/Microsoft.ComponentDetection.Detectors/nuget/NuGetProjectModelProjectCentricComponentDetector.cs, test/Microsoft.ComponentDetection.Detectors.Tests/DotNetComponentDetectorTests.cs
=> Fix reliability issues seen in DotNet experiment

src/Microsoft.ComponentDetection.Detectors/go/Parsers/GoModParser.cs
=> Remove test trace

docs/detector-arguments.md
=> Minor fix to doc string for ignoreDirectories
