microsoft/component-detection

Directory.Packages.props
src/Microsoft.ComponentDetection.Contracts/Microsoft.ComponentDetection.Contracts.csproj

Targeting netstandard2.0 for our contracts allows them to be more portable across multiple versions of .NET. There is zero impact to performance as this project contains no logic.

Target netstandard2.0 for contracts

---

.github/workflows/build-release.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/gen-docs.yml
.github/workflows/publish-release-snapshot.yml
.github/workflows/test-linux.yml
.github/workflows/verify-snapshot.yml
Directory.Build.props
Directory.Packages.props
README.md
global.json
src/Microsoft.ComponentDetection.Contracts/TypedComponent/PodComponent.cs
src/Microsoft.ComponentDetection.Detectors/Microsoft.ComponentDetection.Detectors.csproj
src/Microsoft.ComponentDetection.Detectors/linux/LinuxScanner.cs

Changes include:
- Update `global.json` to require at least .NET Core 3.1.300 (this version specifically is required for centrally managing NuGet packages
- Update GitHub Actions to install .NET Core 3.1
- Update `README.md` to reflect the new requirements
- Fully qualify a constructor in `PodComponent`
- Add `morelinq` dependency to get `DistinctBy`
Closes #18

Target .NET Core 3.1

---

README.md
docs/creating-a-new-detector.md
docs/detectors/README.md
docs/detectors/poetry.md
docs/feature-overview.md
src/Microsoft.ComponentDetection.Detectors/poetry/Contracts/PoetryLock.cs
src/Microsoft.ComponentDetection.Detectors/poetry/Contracts/PoetryPackage.cs
src/Microsoft.ComponentDetection.Detectors/poetry/Contracts/PoetrySource.cs
src/Microsoft.ComponentDetection.Detectors/poetry/PoetryComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PoetryComponentDetectorTests.cs

This detects python dependencies from poetry lockfiles.

Add poetry detector

---

docs/detectors/go.md

This updates the go docs to reflect the current and future desired state of the go detector.

Update go detection docs

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
src/Microsoft.ComponentDetection.Detectors/rust/RustCrateDetector.cs
src/Microsoft.ComponentDetection.Detectors/rust/RustCrateV2Detector.cs
src/Microsoft.ComponentDetection.Detectors/rust/SemVer/Desugarer.cs
test/Microsoft.ComponentDetection.Detectors.Tests/RustCrateDetectorTests.cs

If you specify a dependency with "x.y.z" in Cargo.toml, then that dependency (and it's dependency tree) is only detected if the version of the dependency in Cargo.lock is "x.y.z".
This doesn't match cargo's behaviour, which treats "x.y.z" like "^x.y.z": https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio
I've updated the Rust detector to match cargo's behaviour, and added a test to verify that such dependencies are now picked up by component governance.
The fix is to update the caret desugarar regex to make the caret optional.
I also fixed the vscode dev container files to use .NET 3.1, to match https://github.com/microsoft/component-detection/pull/19

Fix Rust component detector to support "x.y.z" version specifiers in Cargo.toml

---

src/Microsoft.ComponentDetection.Contracts/Internal/NpmAuthor.cs
src/Microsoft.ComponentDetection.Contracts/TypedComponent/NpmComponent.cs
src/Microsoft.ComponentDetection.Contracts/TypedComponent/NugetComponent.cs
src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/nuget/NuGetComponentDetector.cs
test/Microsoft.ComponentDetection.Contracts.Tests/TypedComponentSerializationTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmDetectorTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmTestUtilities.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NuGetComponentDetectorTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NugetTestUtilities.cs
test/Microsoft.ComponentDetection.Detectors.Tests/Utilities/TestUtilityExtensions.cs

Added author Detection for NpmComponents and NugetComponent
[Executive Order](https://www.whitehouse.gov/briefing-room/presidential-actions/2021/05/12/executive-order-on-improving-the-nations-cybersecurity/) requirements 4. e.x. and 4.e.vi. require provenance (origination) information of both open-source software and software code and components. 
This change enables component detection to extract author information for NPM packages from `package.json` files and for Nuget Component from `.nuspec` file.

Added author detection for Npm and Nuget Component

---

src/Microsoft.ComponentDetection.Detectors/pip/IPyPiClient.cs
src/Microsoft.ComponentDetection.Detectors/pip/PipComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/pip/PythonVersion.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PythonVersionTests.cs

Our PipComponentDetector is having issues resolving for dev dependency versions that do not have any number as suffix, e.g. `0.5.7.dev`. This causes `IPyPiClient` to parse that version as if it were a release candidate `0.5.7` and consequently throws errors when adding it to dictionary, see line below: https://github.com/microsoft/component-detection/blob/6176381b4dfefe649cc51be95a5ead764e3e5721/src/Microsoft.ComponentDetection.Detectors/pip/IPyPiClient.cs#L213
1. Create a `requirements.txt` file
2. Add a dependency on `nltk==3.6.2`
3. Run de detector look at the failure caused by [ntlk -> joblib](https://github.com/nltk/nltk/blob/6797ee3958fe3fa0192d347b26ea0fc433b8bfc5/pip-req.txt#L14) version parsing.
Add a new property that stores the `dev` label, and set the `devNumber` version to 0 …

Fix Pypi Dev version parsing

---

test/Microsoft.ComponentDetection.Detectors.Tests/PythonVersionTests.cs

Add a missing Pip test to our suite that verifies the correct handling of a "dev" version.

Add Pypi Dev parsing test

---

src/Microsoft.ComponentDetection.Common/TabularStringFormat.cs
src/Microsoft.ComponentDetection.Detectors/linux/LinuxContainerDetector.cs
src/Microsoft.ComponentDetection.Orchestrator/ArgumentHelper.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorRegistryService.cs
test/Microsoft.ComponentDetection.Common.Tests/ComponentStreamEnumerableTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NuGetProjectModelProjectCentricComponentDetectorTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PythonCommandServiceTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/YarnLockDetectorTests.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/GraphTranslationUtilityTests.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/BcdeScanExecutionServiceTests.cs

`Count()` is a LINQ extension method, whereas `Count` is a property of the collection.
See: https://stackoverflow.com/questions/4098186/lists-count-vs-count

refactor: use collection’s count property

---

src/Microsoft.ComponentDetection.Detectors/rust/RustCrateDetector.cs
src/Microsoft.ComponentDetection.Detectors/rust/RustCrateUtilities.cs
src/Microsoft.ComponentDetection.Detectors/rust/RustCrateV2Detector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/RustCrateDetectorTests.cs
test/Microsoft.ComponentDetection.VerificationTests/resources/rust/standard/Cargo.toml

Cargo supports renamed dependencies in Cargo.toml: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml
component-detection currently misses such dependencies, as it uses the renamed dependency name when determining what the root dependencies on. This PR updates component detection to use the real dependency name in such cases.

Support renamed dependencies in Cargo.toml

---

src/Microsoft.ComponentDetection.Detectors/linux/LinuxContainerDetector.cs
src/Microsoft.ComponentDetection.Detectors/linux/LinuxScanner.cs

When Docker layers are empty there is a possibility that the digest ID is constant between layer indexes. Previously that would cause an exception in the `.ToDictionary` call in LinuxScanner.cs where it expects unique keys.

Handle duplicate DiffId docker image layers

---

Directory.Packages.props
src/Microsoft.ComponentDetection.Contracts/Microsoft.ComponentDetection.Contracts.csproj
test/Microsoft.ComponentDetection.Contracts.Tests/Microsoft.ComponentDetection.Contracts.Tests.csproj

This package was renamed as part of reviving the underlying repo.
See: https://github.com/package-url/packageurl-dotnet/pull/10 and https://github.com/package-url/packageurl-dotnet/pull/13

Move from PackageUrl package to packageurl-dotnet

---

src/Microsoft.ComponentDetection.Common/EnvironmentVariableService.cs
src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs
test/Microsoft.ComponentDetection.Common.Tests/EnvironmentVariableServiceTests.cs

The environment variable EnableGoCliScan existence gates usage of the Go
CLI tools for determing what modules are in-use.  The current check does
a get of the environment variable, and if it exists behavior is enabled.
On Windows this is case-insensitive, but on Linux (or MacOS) this is
case-sensitive so the user must exactly use the casing of
'EnableGoCliScan'.
Our CI system automatically capitalizes all environment variables when
they are defined, so EnableGoCliScan becomes ENABLEGOCLISCAN.  I am not
aware of a way to control this behavior, so there is no way to enable Go
CLI tooling.  My fix is to treat all environment variable exitence
checks as case-insensitive.

Support case-insensitive on non-Windows OSs.

---

src/Microsoft.ComponentDetection.Detectors/yarn/YarnLockComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/YarnLockDetectorTests.cs

It's possible, but rare, for yarn dependencies in the same block to have different names. This is a partial fix for #68, but more investigation may be required.

fix: log a warning when duplicate components are found in a yarn.lock

---

src/Microsoft.ComponentDetection.Detectors/cocoapods/PodComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PodDetectorTest.cs

Resolves #50 by normalizing all git@ references to https:// so Uri creation does not fail.

Normalize Podfile.lock Git Uris to support git@

---

docs/detectors/go.md
docs/detectors/pip.md
docs/environment-variables.md

docs: document environment variables

---

Directory.Packages.props
src/Microsoft.ComponentDetection.Common/EnvironmentVariableService.cs
src/Microsoft.ComponentDetection.Common/Telemetry/Records/PyPiCacheTelemetryRecord.cs
src/Microsoft.ComponentDetection.Contracts/IEnvironmentVariableService.cs
src/Microsoft.ComponentDetection.Detectors/Microsoft.ComponentDetection.Detectors.csproj
src/Microsoft.ComponentDetection.Detectors/pip/IPyPiClient.cs
test/Microsoft.ComponentDetection.Common.Tests/BaseDetectionTelemetryRecordTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PyPiClientTests.cs

Updates the caching mechanism in IPyPiClient from using a ConcurrentDictionary to a Microsoft.Extensions.Caching.Memory MemoryCache which allows setting a maximum number of cache entries and a cache entry expiration time. By limiting the number of entries the memory usage will be lowered and because of expiration time if the tool has not finished by the time the cache is no longer being used memory will be freed before exiting the program.
For users that need additional configuration (potentially due to memory constraints), allow them to set a maximum number of cache entries using the PyPiMaxCacheEntries environment variable.
This resolves the issue #35

Migrate IPyPiClient cache to LRU MemoryCache

---

src/Microsoft.ComponentDetection.Contracts/DetectorClass.cs
src/Microsoft.ComponentDetection.Contracts/TypedComponent/ComponentType.cs
src/Microsoft.ComponentDetection.Contracts/TypedComponent/SpdxComponent.cs
src/Microsoft.ComponentDetection.Detectors/spdx/Spdx22ComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/SPDX22ComponentDetectorTests.cs
test/Microsoft.ComponentDetection.VerificationTests/resources/spdx/manifest.spdx.json

This PR introduces detector for SPDX 2.2 files and SpdxComponent type. Initial implementation parses JSON SPDX file and extracts minimal set of information about the SPDX document necessary to link SPDX file in other SPDX files. It implements `IDefaultOffComponentDetector` interface.
This detector could eventually be expanded to retrieve information about what SPDX documents describes and what are dependencies for a product that document describes.
Detector has been tested inside Microsoft teams in external referencing feature for SBOMs and has been live in SBOM generation process for about a month now.

Initial implementation of SPDX22 Detector

---

test/Microsoft.ComponentDetection.Common.Tests/DockerServiceTests.cs

Currently we're using an Ubuntu image, which is >100MB for unit tests. This is a large image for build machines and users to pull in for a single unit test, especially when we're only checking annotations.
This PR instead uses the `docker.io/library/hello-world:latest` image, which weighs in at a whopping 13KB.

refactor(linux): use a smaller image to test base image annotations

---

src/Microsoft.ComponentDetection.Detectors/maven/MavenParsingUtilities.cs
test/Microsoft.ComponentDetection.Detectors.Tests/MavenParsingUtilitiesTests.cs

A bug was introduced in [this](https://github.com/microsoft/component-detection/commit/3a17feb7e1f5cf8acefc03a53adf932a2a5b7b5c) commit, 
which resulted in invalid scope if there was left over string in the scope substring.
an example [build break](https://github.com/microsoft/componentdetection-azdo/runs/5858218730?check_suite_focus=true) as a result of this was observed in azdo. 
- new unit test for this special parsing use case.
- Tested locally to detect maven components. 
- All existing unit tests successfully passed.

Bug Fix: While parsing maven scope, discard left-over string if present.

---

src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/GoComponentDetectorTests.cs

A go package can have a cyclic dependency, for example:
```
github.com/prometheus/common@v0.4.1 github.com/gogo/protobuf@v1.1.1
github.com/prometheus/client_golang@v1.0.0 github.com/prometheus/common@v0.4.1
github.com/prometheus/common@v0.10.0 github.com/prometheus/client_golang@v1.0.0 
github.com/prometheus/client_golang@v1.7.1 github.com/prometheus/common@v0.10.0 
github.com/prometheus/common@v0.26.0 github.com/prometheus/client_golang@v1.7.1 
github.com/prometheus/client_golang@v1.11.0 github.com/prometheus/common@v0.26.0 
github.com/prometheus/common@v0.32.1 github.com/prometheus/client_golang@v1.11.0 
github.com/prometheus/client_golang@v1.12.1 github.com/prometheus/common@v0.32.1
```
Cyclic dependencies break how the current Go CLI detector works, causing it to break silently and …

Fix Go CLI cyclic dependency graph

---

docs/detectors/go.md
docs/feature-overview.md
src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/GoComponentDetectorTests.cs

Currently for Golang projects component detection works by scanning the go.sum file or using `go mod graph` command as an alternative, but results should be the same as using go.sum file because go mod graph prints out all the versions in the graph. This means we are over detecting modules of versions that are no longer included in the build binaries.
Use [go list -m all](https://go.dev/ref/mod#go-list-m) command to find the actual versions of the components [used during a build](https://go.dev/ref/mod#glos-build-list) as it uses the [minimal version selection](https://go.dev/ref/mod#minimal-version-selection) algorithm. That command does not generate a graph for us, hence by running both `go mod graph` and `go list -m all`, we are able to prune all the dependencies that were not included …

Go CLI detector enhancement (`go list -m all`)

---

docs/detectors/go.md
docs/environment-variables.md
src/Microsoft.ComponentDetection.Common/EnvironmentVariableService.cs
src/Microsoft.ComponentDetection.Contracts/IEnvironmentVariableService.cs
src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs
src/Microsoft.ComponentDetection.Orchestrator/Orchestrator.cs
test/Microsoft.ComponentDetection.Common.Tests/EnvironmentVariableServiceTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/GoComponentDetectorTests.cs

Enabling Go cli detector by default.
Previously, the Go-Detector by default scanned the manifest and generated components. We were using `EnableGoCliScan` env. variable to activate the Go Cli Detector. With this change, the use of `EnableGoCliScan` is removed. The Go detector by default uses Cli scan. 
To manually override this behavior, new env. variable `DisableGoCliScan` is introduced. 
- Unit tests
- Locally, ran the component-detection on [componentdetection-verification/tree/main/projects/go/helm](https://github.com/microsoft/componentdetection-verification/tree/main/projects/go/helm)
- without setting the env. variable, validated that go cli scan was ran. approx. 400 components generated. 
- when `DisableGoCliScan=true` env. variable, validated that GoDetector with manifest scan …

Enable GoCliDetector by default. Using env variable 'DisableGoCliDetector=true" to manually disable GoCliDetector.

---

src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs

Added error message to expose go cli error in the build output. 
- Go cli output:
```
go: errors parsing go.mod:
C:\Repos\component-detection\test\Microsoft.ComponentDetection.VerificationTests\resources\go\go.mod:5: unknown directive: requie
```
- Build logs:
```
[ERROR] Go CLI command "go list -m -json all" failed with error:
go: errors parsing go.mod:
C:\Repos\component-detection\test\Microsoft.ComponentDetection.VerificationTests\resources\go\go.mod:5: unknown directive: requie
```

In Go detector, Added error log to expose go cli error.

---

docs/detectors/pnpm.md
src/Microsoft.ComponentDetection.Detectors/pnpm/PnpmComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PnpmDetectorTests.cs

When the detector found a link dependency it failed the detection and the rest of components where not scanned. This change ignore the link dependencies and allow the dectector to continue parsing the rest of the file.

Fixed pnpm detector failing parsing link dependencies

---

renovate.json

As part of a pilot rollout of [Renovate](https://github.com/renovatebot/renovate/), I've enrolled our repository. This configuration is a minimal configuration, that imports the [`config:base`](https://docs.renovatebot.com/presets-config/#configbase) preset.

chore: add basic renovate configuration

---

src/Microsoft.ComponentDetection.Contracts/BcdeModels/TypedComponentConverter.cs
src/Microsoft.ComponentDetection.Contracts/TypedComponent/VcpkgComponent.cs
test/Microsoft.ComponentDetection.Detectors.Tests/VcpkgComponentDetectorTests.cs

VcpkgComponent detector is still in piloting phase, which means is disabled by default. We noticed we were missing the TypedComponentConverter for this new type, which was breaking any wrapper tool looking to deserialize the output json file.
We also noticed that port versions are set as integers on GitHub rather than string, hence we are updating the component to reflect this value.
See sample port version file in VCPKG Forge: https://github.com/microsoft/vcpkg/blob/master/versions/w-/wampcc.json

Add missing VcpkgComponent converter and use port version as int

---

src/Microsoft.ComponentDetection.Detectors/poetry/PoetryComponentDetector.cs

#167 enabled the poetry detector by default. We don't want to globally enable it yet, but instead move from an opt-in to an experimental detector.

fix: make poetry an experimental detector

---

src/Microsoft.ComponentDetection.Contracts/DetectorClass.cs
src/Microsoft.ComponentDetection.Detectors/dockerfile/DockerfileComponentDetector.cs

Previously it was incorrectly listed as `GoMod`. It requires a new `DockerReference` type instead.

fix: dockerfile detector detector class type

---

test/Microsoft.ComponentDetection.TestsUtilities/Microsoft.ComponentDetection.TestsUtilities.csproj

IsPackable property was removed recently with the assumption it didn't add value outside the tests in this repo, but it does, it helps wrappers and users do unit tests for the detectors without having to start from scratch.

Packable TestUtilities project

---

Directory.Packages.props
src/Microsoft.ComponentDetection.Detectors/linux/LinuxContainerDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/LinuxContainerDetectorTests.cs

If a container image has a image.base.ref.name of scratch then determine that there is no base image, rather than trying to pull "scratch".
In v1.1.9 component-detection tries to pull the "scratch@" image, which fails causing the following log to be displayed:
```
[INFO] Base image scratch@ could not be found locally and could not be pulled. Results will not be mapped to base image layers 
```
In v1.2.4 component-detection still tries to pull the "scratch@" image but this time the TryPullImageAsync call at https://github.com/microsoft/component-detection/blob/0319816fabb129ec043a270bc0fb1d9763986101/src/Microsoft.ComponentDetection.Detectors/linux/LinuxContainerDetector.cs#L225 must be succeeding, as component-detection doesn't omit that log, but subsequently hits an error like
```
[WARN] …
```

Special case scratch base image

---

src/Microsoft.ComponentDetection.Detectors/nuget/NuGetPackagesConfigDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/Microsoft.ComponentDetection.Detectors.Tests.csproj
test/Microsoft.ComponentDetection.Detectors.Tests/nuget/NuGetPackagesConfigDetectorTests.cs
test/Microsoft.ComponentDetection.VerificationTests/resources/nuget/packages-config/packages.config

This change adds a new `NuGetPackagesConfigDetector` for 'old-style' NuGet projects that use `packages.config`. The intention is to replace the `NuGetComponentDetector` with this detector, as it is overreporting NuGet components (due to how nuget restores packages on disk).
TODO:
- See https://github.com/search?q=org%3Adotnet+filename%3Apackages.config
References:
- [packages.config reference](https://docs.microsoft.com/en-us/nuget/reference/packages-config)
- [Migrate from packages.config to PackageReference](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference)
Signed-off-by: Jamie Magee <jamagee@microsoft.com>

feat: add `NuGetPackagesConfigDetector`

---

Directory.Packages.props

I believe we were incorrectly using the `**` pattern. Rolling back `dotnet.glob` as a quick fix until we can investigate more.
Sources:
- https://github.com/microsoft/component-detection/releases/tag/v1.2.1
- https://github.com/microsoft/component-detection/pull/138
- https://github.com/dazinator/DotNet.Glob/issues/65
- https://github.com/dazinator/DotNet.Glob/commit/f1ee0efcc82c375e8124f08053190509eeb3de45

fix: rollback dotnet.glob from 2.1.4 to 2.1.1

---

.editorconfig
Directory.Build.props

This change:
- Enables `TreatWarningsAsErrors`
- Disables any analyzers that would currently break the build
I've created an overarching issue to track re-enabling each of these analyzers: #202

refactor: enable `TreatWarningsAsErrors`

---

.editorconfig
test/Microsoft.ComponentDetection.Detectors.Tests/LinuxContainerDetectorTests.cs

Commas should not be preceded by whitespace
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1001.md

refactor: fix SA1001

---

.editorconfig
src/Microsoft.ComponentDetection.Contracts/FileComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/gradle/GradleComponentDetector.cs

inheritdoc should be used with inheriting class
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1648.md

refactor: fix SA1648

---

.editorconfig

Refactor: fix SA1009

---

src/Microsoft.ComponentDetection.Contracts/IComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/vcpkg/VcpkgComponentDetector.cs

As we do Vcpkg rollout, we want to make sure we have good metrics about its performance and unexpected failures across the board by having it running as an experimental detector

Make Vcpkg Experimental detector

---

.editorconfig
src/Microsoft.ComponentDetection.Common/PathUtilityService.cs
src/Microsoft.ComponentDetection.Common/Telemetry/CommandLineTelemetryService.cs
src/Microsoft.ComponentDetection.Contracts/DockerReference.cs
src/Microsoft.ComponentDetection.Detectors/cocoapods/PodComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/ivy/IvyDetector.cs
src/Microsoft.ComponentDetection.Detectors/linux/LinuxContainerDetector.cs
src/Microsoft.ComponentDetection.Detectors/maven/MavenStyleDependencyGraphParser.cs
src/Microsoft.ComponentDetection.Detectors/nuget/NuGetComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/pip/IPyPiClient.cs
src/Microsoft.ComponentDetection.Detectors/rust/SemVer/Range.cs
src/Microsoft.ComponentDetection.Orchestrator/ArgumentHelper.cs
src/Microsoft.ComponentDetection.Orchestrator/CommandLineArgumentsExporter.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DetectorProcessingServiceTests.cs
test/Microsoft.ComponentDetection.TestsUtilities/DetectorTestUtility.cs

Refactor: Fix SA1204

---

.editorconfig
src/Microsoft.ComponentDetection.Common/DockerReference/DockerReferenceUtility.cs
src/Microsoft.ComponentDetection.Contracts/TypedComponent/PodComponent.cs
src/Microsoft.ComponentDetection.Detectors/maven/IMavenCommandService.cs
src/Microsoft.ComponentDetection.Detectors/maven/MavenCommandService.cs
src/Microsoft.ComponentDetection.Detectors/maven/MavenStyleDependencyGraphParserService.cs
src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/pip/PythonCommandService.cs
src/Microsoft.ComponentDetection.Detectors/pip/PythonResolver.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/GraphTranslation/DefaultGraphTranslationService.cs
test/Microsoft.ComponentDetection.Common.Tests/EnvironmentVariableServiceTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/MavenCommandServiceTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/MavenParsingUtilitiesTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/SPDX22ComponentDetectorTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/VcpkgComponentDetectorTests.cs
test/Microsoft.ComponentDetection.TestsUtilities/DetectorTestUtility.cs

Using directive for '...' should appear before directive for '...'
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1208.md

refactor: fix SA1208

---

src/Microsoft.ComponentDetection.Detectors/dockerfile/DockerfileComponentDetector.cs

Related: #196 
Added a try-catch statement in the OnFileFound method for the Docker component because component detection was attempting to scan files that are named like a Dockerfile but aren't really a Dockerfile which was causing an error.

Fix for Bug 196

---

Directory.Packages.props

This was originally upgraded in #144 but is causing deadlocks for some users. The long-term fix is outlined in #221, but this workaround is sufficient to temporarily resolve the issue.

fix: downgrade `System.Threading.Tasks.Dataflow` from `4.11.1` to `4.9.0`

---

.editorconfig
test/Microsoft.ComponentDetection.Detectors.Tests/nuget/NuGetPackagesConfigDetectorTests.cs

Using directive for namespace '...' should be qualified https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1135.md

refactor: fix SA1135

---

.editorconfig
src/Microsoft.ComponentDetection.Detectors/rust/RustCrateUtilities.cs

Remove fix occurrences warning SA1114
Parameter list should follow declaration.
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1114.md

Refactor: Fix warning SA1114

---

src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetectorWithRoots.cs

Changed Logger.LogBuildWarning to Logger.LogInfo in npm detector files to prevent unnecessary build warnings. Related: #199

Fix Issue 199

---

src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/GoComponentDetectorTests.cs

Fix for issue #189: Changed "go list -m -json all" to "go list -mod=readonly -m -json all"

Fix for Issue 189 (changing go list -m -json all) 

---

.editorconfig
src/Microsoft.ComponentDetection.Common/DockerReference/DockerRegex.cs
src/Microsoft.ComponentDetection.Common/FastDirectoryWalkerFactory.cs
src/Microsoft.ComponentDetection.Common/PathUtilityService.cs
src/Microsoft.ComponentDetection.Common/Telemetry/TelemetryRelay.cs
src/Microsoft.ComponentDetection.Contracts/FileComponentDetector.cs
src/Microsoft.ComponentDetection.Contracts/IComponentDetector.cs
src/Microsoft.ComponentDetection.Contracts/IComponentRecorder.cs
src/Microsoft.ComponentDetection.Contracts/IComponentStreamEnumerableFactory.cs
src/Microsoft.ComponentDetection.Contracts/IPathUtilityService.cs
src/Microsoft.ComponentDetection.Detectors/linux/LinuxContainerDetector.cs
src/Microsoft.ComponentDetection.Detectors/nuget/NuGetComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/pip/PipDependencySpecification.cs
src/Microsoft.ComponentDetection.Detectors/pip/PythonVersionUtilities.cs
src/Microsoft.ComponentDetection.Detectors/rust/RustCrateUtilities.cs
src/Microsoft.ComponentDetection.Detectors/yarn/Parsers/YarnBlockFile.cs
src/Microsoft.ComponentDetection.Detectors/yarn/YarnLockComponentDetector.cs

[Issue #202 ](https://github.com/microsoft/component-detection/issues/202)
- SA-1614, 
- SA-1615, 
- SA-1616, 
- SA-1617

Analyzer Warnings SA-1614, SA-1615, SA-1616, SA-1617

---

.editorconfig
.github/workflows/release.yml

Fix release failure for 2.0.0. 
Release 2.0.0 [failed](https://github.com/microsoft/component-detection/actions/runs/3200952692/jobs/5228440236) with net6 migration. 
- error `IL3000` is avoided by suppressing it `.editorconfig` file.
- error `IL2026` is avoided by disabling [TrimmedPublishing ](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained) during release. 
ran `dotnet publish --configuration Release --output ./bin --self-contained --runtime win-x64 -p:PublishSingleFile=true -p:DebugType=None -p:PublishTrimmed=false ./src/Microsoft.ComponentDetection` in local.
- command succeeds.
- validated that published artifacts are not larger than the previous one.

fix release failure.

---

.github/workflows/release.yml

Previous release  (2.0.1) failed during publishing step ([failure](https://github.com/microsoft/component-detection/actions/runs/3206317150/jobs/5240012749)). This is a fix for it. 
Rootcause: 
after .net6 migration the default publishing step was generating multiple asset files in the `./bin` folder. This was causing failure in `Publish CLI tool` step, since its only expecting single file under `./bin`. 
due to .net6 migration , it was required that we add `-p:IncludeAllContentForSelfExtract=true ([source](https://learn.microsoft.com/en-us/answers/questions/296816/self-contained-single-file-does-not-produce-a-sing.html)).
- locally ran `dotnet publish --configuration Release --output ./bin --self-contained --runtime win-x64 -p:PublishSingleFile=true …

Fixed release failure

---

src/Microsoft.ComponentDetection.Detectors/vcpkg/VcpkgComponentDetector.cs

Make vcpkg logging debug and info instead of warning for non-errors

Make vcpkg logging non-warning

---

.editorconfig
src/Microsoft.ComponentDetection.Detectors/ruby/RubyComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/rust/RustCrateDetector.cs
src/Microsoft.ComponentDetection.Detectors/rust/SemVer/ComparatorSet.cs
src/Microsoft.ComponentDetection.Detectors/rust/SemVer/PartialVersion.cs

[CA1820: Test for empty strings using string length
](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1820)

refactor: fix CA1820

---

Directory.Packages.props

We have hit issues with the PoetryDetector. 
```
[ERROR] SafelyExecuteAsync logged TomlException: (991,2) : error : Unable to set the property extras on object type Microsoft.ComponentDetection.Detectors.Poetry.Contracts.PoetryLock.
```
I believe this is due to an issue with Tomlyn where defaulting missing tables didn't work for `object` types. This has now been fixed in version [0.15.1](https://github.com/xoofx/Tomlyn/releases/tag/0.15.1).
[Corresponding PR](https://github.com/xoofx/Tomlyn/pull/44)
Could I please request a release of component-detection once this change is in, to fixup my pipelines? 
Question for reviewer:
- Why did the testing in `component-detection` not identify this issue and could you suggest some additional testing to add to verify that PRs haven't broken …

Update tomlyn to 0.15.1 fixing PoetryDetector

---

.editorconfig
src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/maven/MavenParsingUtilities.cs
src/Microsoft.ComponentDetection.Detectors/maven/MavenStyleDependencyGraphParser.cs
src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetectorWithRoots.cs
src/Microsoft.ComponentDetection.Detectors/nuget/NuGetComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/nuget/NuGetProjectModelProjectCentricComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/pip/PythonResolver.cs
src/Microsoft.ComponentDetection.Detectors/rust/SemVer/Comparator.cs
src/Microsoft.ComponentDetection.Detectors/rust/SemVer/Range.cs
test/Microsoft.ComponentDetection.Detectors.Tests/MavenStyleDependencyGraphParserTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PipComponentDetectorTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PipResolverTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/RustDependencySpecifierTest.cs
test/Microsoft.ComponentDetection.Detectors.Tests/YarnLockDetectorTests.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/BcdeScanExecutionServiceTests.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DetectorRestrictionServiceTests.cs
test/Microsoft.ComponentDetection.VerificationTests/ComponentDetectionIntegrationTests.cs

fixed following analyzer warning
- fix IDE0031: Null check can be simplified
- IDE0042: Variable declaration can be deconstructed
- IDE0018: Variable declaration can be inlined
- IDE0017: Object initialization can be simplified
- IDE0004: Cast is redundant.
- IDE0007: use 'var' instead of explicit type
- IDE0016: Null check can be simplified

fix IDE0031, IDE0042, IDE0018, IDE0017, IDE0004, IDE0007, IDE0016

---

Directory.Build.props

The `TargetLatestRuntimePatch` property forces the `runtimeconfig.json`[^1] of our executables to specify the latest version of the runtime that the SDK we used to build knows about, instead of targeting `6.0.xxx`. Forcing this higher version makes any executables we produce less portable.
[^1]: https://learn.microsoft.com/en-us/dotnet/core/runtime-config/

ci: remove `TargetLatestRuntimePatch` property

---

src/Microsoft.ComponentDetection.Common/FileWritingService.cs

Related to https://github.com/microsoft/component-detection/issues/279

Use extended log file names format to prevent collisions in concurrent builds

---

test/Directory.Build.props
test/Microsoft.ComponentDetection.Common.Tests/Microsoft.ComponentDetection.Common.Tests.csproj
test/Microsoft.ComponentDetection.Contracts.Tests/Microsoft.ComponentDetection.Contracts.Tests.csproj
test/Microsoft.ComponentDetection.Detectors.Tests/Microsoft.ComponentDetection.Detectors.Tests.csproj
test/Microsoft.ComponentDetection.Orchestrator.Tests/Microsoft.ComponentDetection.Orchestrator.Tests.csproj
test/Microsoft.ComponentDetection.TestsUtilities/Microsoft.ComponentDetection.TestsUtilities.csproj

The `Microsoft.NET.Test.Sdk` automatically creates an entrypoint for test projects and enables them to run. The `Microsoft.ComponentDetection.TestsUtilities` project is a shared library that is used in other test projects, and is not a runnable project itself.
This change moves `Microsoft.NET.Test.Sdk` from `test/Directory.Build.props`, which is inherited by all projects in the `test` directory, to each individual test project that needs it.

test: exclude `Microsoft.NET.Test.Sdk` from `Microsoft.ComponentDetection.TestsUtilities` project

---

.editorconfig
.github/workflows/snapshot-publish.yml
.github/workflows/snapshot-verify.yml
src/Microsoft.ComponentDetection.Contracts/BcdeModels/TypedComponentConverter.cs
src/Microsoft.ComponentDetection.Contracts/DockerReference.cs
src/Microsoft.ComponentDetection.Contracts/TypedComponent/SpdxComponent.cs
test/Microsoft.ComponentDetection.VerificationTests/resources/VerificationTest.ps1
test/Microsoft.ComponentDetection.VerificationTests/resources/dockerFiles/Dockerfile
test/Microsoft.ComponentDetection.VerificationTests/resources/dockerFiles/alpine.dockerfile
test/Microsoft.ComponentDetection.VerificationTests/resources/dockerFiles/atlassian.dockerfile
test/Microsoft.ComponentDetection.VerificationTests/resources/dockerFiles/python.dockerfile
test/Microsoft.ComponentDetection.VerificationTests/resources/dockerFiles/ubuntu.dockerfile

- Enabled verification tests for `DockerReference` and `SPDX22SBOM` detectors
- minor bug fix in `DockerRefernce` detection that detected Repository kind as canonical.
- bug fix in de-serialization of "spdx" component during verification tests. 
Note: verification tests are expected to fail because new detectors are enabled in this PR.

added verification for dockerfile and spdx detector, minor bug fixes

---

.editorconfig

Add the IDE0053, IDE0200, CA1311, CA1852, and CA1854 exlcusions to .editorconfig to avoid build breaks.
They will be addressed as part of #202

Add new exclusions to .editorconfig

---

src/Microsoft.ComponentDetection.Orchestrator/ArgumentSets/BaseArguments.cs
src/Microsoft.ComponentDetection.Orchestrator/ArgumentSets/IScanArguments.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/BcdeScanExecutionService.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorListingCommandService.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorRegistryService.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/IDetectorRegistryService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/BcdeScanExecutionServiceTests.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DetectorListingCommandServiceTests.cs

On most runs of component detection, the /Plugins folder is searched for additional detector assemblies, but the folder does not exist, showing a [WARN] message like
```
[WARN] Provided search path D:\a\_tasks\SomeFolder\1.1.48\detection\Plugins does not exist.
```
This adds a default parameter to allow skipping the check for additional detectors in /Plugins without modifying logic of additional directory search parameters.

Add param to skip searching /Plugins for extra detectors

---

src/Microsoft.ComponentDetection.Common/PathUtilityService.cs

After #330 CA1831 was being flagged in PathUtilityService (on some build machines) due to the new use of [..1] indexers. This PR adds the .AsSpan call to avoid making data copies.
`Microsoft.ComponentDetection.Common\PathUtilityService.cs(85,77): error CA1831: Use 'AsSpan' instead of the 'System.Range'-based indexer on 'string' to avoid creating unnecessary data copies`

Address CA1831 after path substring changes

---

.editorconfig
src/Microsoft.ComponentDetection.Detectors/IComponentGovernanceOwnedDetectors.cs
src/Microsoft.ComponentDetection.Detectors/poetry/Contracts/PoetrySource.cs
src/Microsoft.ComponentDetection.Detectors/poetry/PoetryComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/rust/Contracts/CargoPackage.cs
src/Microsoft.ComponentDetection.Detectors/rust/Contracts/CargoToml.cs
src/Microsoft.ComponentDetection.Detectors/rust/DependencySpecification.cs
src/Microsoft.ComponentDetection.Detectors/rust/RustCrateDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/RustDependencySpecifierTest.cs

Related to #202  
fixed 
- CA1707: Identifiers should not contain underscores
- SA1300: Element Must Begin With Upper CaseLetter
- CA1040: Avoid empty interfaces

Fix Analyzer warnings: CA1707, CA1300, CA1040

---

src/Microsoft.ComponentDetection.Common/Logger.cs
src/Microsoft.ComponentDetection.Orchestrator/Orchestrator.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/BcdeScanExecutionService.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorRegistryService.cs

Add a line prefix override for the Logger class to skip printing [INFO], [VERBOSE], etc. and update log grouping slightly.

Update CD logging to include override for line prefix

---

src/Microsoft.ComponentDetection.Detectors/nuget/NuGetPackagesConfigDetector.cs

The NuGetPackagesConfigDetector is no longer an expiremental detector. After going through validation, we are turning this detector on by default.

Enabling the NuGetPackagesConfigDetector to run by default.

---

Dockerfile
src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs

After #107 and #162 we've migrated the target framework, and related dependencies, to .NET 6. However, the container image at the root of the repository was missed.
This PR:
- changes the base images to their `6.0-cbl-mariner2.0` tags
- Removes `gradle` from the final image (It doesn't appear to be available for Mariner 2.0)
- Removes trimming (Component Detection is incompatible with trimming due to our use of reflection)
- Makes a small linting fix in `DetectorProcessingService.cs` (IDE0055)

chore: bump container image to .NET 6

---

src/Microsoft.ComponentDetection.Detectors/nuget/NuGetPackagesConfigDetector.cs

Without this we'll throw a `PackagesConfigReaderException`, and while duplicate packages in `packages.config` is not ideal, it is a supported scenario.

fix(nuget): allow duplicate packages in `pacakge.config`

---

src/Microsoft.ComponentDetection.Common/Microsoft.ComponentDetection.Common.csproj
src/Microsoft.ComponentDetection/Microsoft.ComponentDetection.csproj
test/Microsoft.ComponentDetection.Common.Tests/Microsoft.ComponentDetection.Common.Tests.csproj
test/Microsoft.ComponentDetection.Contracts.Tests/Microsoft.ComponentDetection.Contracts.Tests.csproj
test/Microsoft.ComponentDetection.Detectors.Tests/Microsoft.ComponentDetection.Detectors.Tests.csproj
test/Microsoft.ComponentDetection.Orchestrator.Tests/Microsoft.ComponentDetection.Orchestrator.Tests.csproj
test/Microsoft.ComponentDetection.TestsUtilities/Microsoft.ComponentDetection.TestsUtilities.csproj

Add explicit reference to System.Threading.Tasks.Dataflow to avoid version resolution conflicts.

Add explicit reference to System.Threading.Tasks.Dataflow

---

src/Microsoft.ComponentDetection.Detectors/pip/IPyPiClient.cs

Increased number of default cache entries

---

Directory.Packages.props
src/Microsoft.ComponentDetection.Orchestrator/Extensions/ServiceCollectionExtensions.cs
src/Microsoft.ComponentDetection.Orchestrator/Microsoft.ComponentDetection.Orchestrator.csproj
src/Microsoft.ComponentDetection/Microsoft.ComponentDetection.csproj

The first step in moving away from [Managed Extensibility Framework (MEF)][1] to the more modern Dependency Injection framework
[1]: https://learn.microsoft.com/en-us/dotnet/framework/mef/

refactor: add `Microsoft.Extensions.DependencyInjection` dependencies

---

src/Microsoft.ComponentDetection.Detectors/pip/PythonCommandService.cs
src/Microsoft.ComponentDetection.Orchestrator/Orchestrator.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PythonCommandServiceTests.cs

Fixes #313 by checking the Setup.py command output against the empty result set of None after trimming. If the output is only None and not the package None, skip any parsing attempts for the file.

Resolve Python2 setup.py incorrect None package detection

---

src/Microsoft.ComponentDetection.Orchestrator/ArgumentSets/BaseArguments.cs
src/Microsoft.ComponentDetection.Orchestrator/ArgumentSets/IScanArguments.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/BcdeScanExecutionServiceTests.cs

`AdditionalPluginDirectories` and `SkipPluginsDirectory` are unnecessary after the migration to dependency injection.

refactor: remove unnecessary arguments

---

src/Microsoft.ComponentDetection.Common/FileWritingService.cs
src/Microsoft.ComponentDetection.Common/IFileWritingService.cs
src/Microsoft.ComponentDetection/Program.cs
test/Microsoft.ComponentDetection.Common.Tests/FileWritingServiceTests.cs

This adds buffering to the `FileWritingService`. Previously, every log message synchronously called `File.AppendAllText`.
This should help increase performance for #373 and across the board.
Profiling Component Detection lead to serious performance gains:
Before:
After:

perf: add buffering to `FileWritingService`

---

src/Microsoft.ComponentDetection.Common/Logger.cs

Within the logger class there is nothing to prevent re-initialization of the log file if there is an external caller to the Init method. This may cause exceptions such as `The process cannot access the file 'C:\Temp\BuildAgent\_work\1\a\GovCompDisc_Log_20230221094929531.log' because it is being used by another process.` where the file can't be overwritten due to already being in use.
Add an early exit to Logger.Init if already initialized to prevent this.

Don't allow re-init of Logger class

---

Directory.Packages.props
src/Microsoft.ComponentDetection.Orchestrator/Microsoft.ComponentDetection.Orchestrator.csproj
src/Microsoft.ComponentDetection.Orchestrator/Orchestrator.cs

In #441, we used a `Serilog.Sinks.File` to output to a log file, but we buffered the log file. This helps us increase our performance massively, but in the event that component detection crashes and the loggers aren't disposed, our logs won’t be flushed to disk.
Wrapping the file sink in an async sink allows us to not have to buffer the file, as all File I/O is done on a background thread and won't block, and will still leave logs intact if CD crashes.

feat: use async sink for the file sync

---

test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DetectorListingCommandServiceTests.cs
test/Microsoft.ComponentDetection.TestsUtilities/ExtensionMethods.cs

Adds a new extension method to `Mock<ILogger<T>>` to allow the capturing of log outputs for tests.

refactor: add logging test extension helpers

---

src/Microsoft.ComponentDetection.Orchestrator/ArgumentSets/BcdeArguments.cs
src/Microsoft.ComponentDetection.Orchestrator/ArgumentSets/IDetectionArguments.cs
src/Microsoft.ComponentDetection.Orchestrator/Orchestrator.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/BcdeScanCommandService.cs

This adds the ability to pass `--PrintManifest` to CD and will then output the scan manifest JSON to stdout.
This PR also updates Serilog to only output to standard error, so that the users can simply redirect stdout.
Closes #246

feat: add `--PrintManifest` option

---

src/Microsoft.ComponentDetection.Orchestrator/Orchestrator.cs

Fixes #387 
This does change the format of the telemetry. `dpkg -l` returns like this:
```
ii  libssl3:amd64                  3.0.2-0ubuntu1.8                        amd64        Secure Sockets Layer toolkit - shared libraries
```
But we could also spawn a bash shell and run:
```bash
dpkg -l | grep libssl | tr -s ' ' | cut -d ' ' -f 2,3,4
```
Which would return cleaner telemetry:
```
libssl3:amd64 3.0.2-0ubuntu1.8 amd64
```

fix: use `dpkg` get OpenSSL version

---

Directory.Build.targets

We've been seeing these nag messages in our build logs for quite some time now:
> MinVer : warning MINVER1008: MinVerDefaultPreReleasePhase is deprecated and will be removed in the next major version. Use MinVerDefaultPreReleaseIdentifiers instead, with an additional "0" identifier. For example, if you are setting MinVerDefaultPreReleasePhase to "preview", set MinVerDefaultPreReleaseIdentifiers to "preview.0" instead.]
We previously set `MinVerDefaultPreReleasePhase` to `preview`, and this PR follows their recommendation and sets `MinVerDefaultPreReleaseIdentifiers` to `preview.0`

fix: update MinVer prerelease tag

---

src/Microsoft.ComponentDetection.Detectors/pip/PipDependencySpecification.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PipDependencySpecifierTests.cs

Properly handles `Rquires-Dist` like so:
```
Requires-Dist: numpy<1.27.0,>=1.19.5
```
Also, properly handles dependencies with optional dependencies in pip `METADATA` or in `requirements.txt`. We ignore them for now.
```
Requires-Dist: PyJWT[crypto] (<3,>=1.0.0)
```

fix: `Requires-Dist` variants & optional deps

---

.github/workflows/snapshot-verify.yml

This updates our `Verify snapshot of test scan` workflow to upload the logs it took scanning the test repo.
This is to help diagnose the recent golang verification failures.

ci: upload snapshot verify logs

---

src/Microsoft.ComponentDetection.Detectors/pip/PipDependencySpecification.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PipDependencySpecifierTests.cs

Fixes a customer issue where if a `Requires-Dist` package has extra whitespace before the version specifier, that whitespace would be captured by the regex and cause an invalid python version specifier.
We could have also changed the regex, but it is already too complex as it supports a wide variety of `Requires-Dist` formats...

fix(pip): trim whitespace in `Requires-Dist`

---

src/Microsoft.ComponentDetection.Detectors/nuget/NuGetComponentDetector.cs

Added conditional operator for name and version variables to prevent NullReferenceException when nuspec file does not contain name/version
#486

Fix: adding conditional operator to prevent NullReferenceException in NugetComponentDetector

---

src/Microsoft.ComponentDetection.Common/Telemetry/Records/NpmLockfileVersionTelemetryRecord.cs
src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetectorWithRoots.cs

Records the `lockfileVersion` in `package-lock.json` for analysis on the impact of #476

chore(npm): add lockfile version telemetry

---

docs/environment-variables.md
src/Microsoft.ComponentDetection.Common/DependencyGraph/DependencyGraph.cs
src/Microsoft.ComponentDetection.Contracts/IComponentRecorder.cs
src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetectorWithRoots.cs
src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentUtilities.cs
test/Microsoft.ComponentDetection.Common.Tests/DependencyGraphTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmDetectorWithRootsTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmTestUtilities.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmUtilitiesTests.cs

feat(npm): add support for lockfile v3

---

src/Microsoft.ComponentDetection.Common/DependencyGraph/DependencyGraph.cs
src/Microsoft.ComponentDetection.Contracts/DetectedComponent.cs
src/Microsoft.ComponentDetection.Contracts/IComponentRecorder.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/GraphTranslation/DefaultGraphTranslationService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DefaultGraphTranslationServiceTests.cs

Individual custom component file locations can't be added due to removal in DefaultGraphTranslationService. The service should verify they are under root and they are relative.#476 
The DefaultGraphTranslationService already  adds the file location where the detector was executed to the components, allow other custom locations to be added under same root (making them relative beforehand)

Accept custom individual component file paths

---

docs/environment-variables.md
src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetectorWithRoots.cs
src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentUtilities.cs
src/Microsoft.ComponentDetection.Detectors/npm/NpmLockfile3Detector.cs
src/Microsoft.ComponentDetection.Detectors/npm/NpmLockfileDetectorBase.cs
src/Microsoft.ComponentDetection.Orchestrator/Extensions/ServiceCollectionExtensions.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmDetectorWithRootsTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmLockfile3DetectorTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmUtilitiesTests.cs

Separates the lock file 3 specific code into a new detector.

refactor(npm): separate lockfile 3 detector

---

src/Microsoft.ComponentDetection.Orchestrator/Experiments/ExperimentService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Experiments/ExperimentServiceTests.cs

An exception may occur when writing the experiment diff to disk or uploading it to Azure Storage, so we should swallow exceptions.

fix: swallow exceptions processing experiments

---

src/Microsoft.ComponentDetection/LoaderInteropConstants.cs

This was required before the migration to dependency injection

refactor: delete `LoaderInteropConstants`

---

src/Microsoft.ComponentDetection.Orchestrator/Experiments/Configs/IExperimentConfiguration.cs
src/Microsoft.ComponentDetection.Orchestrator/Experiments/Configs/NewNugetExperiment.cs
src/Microsoft.ComponentDetection.Orchestrator/Experiments/Configs/NpmLockfile3Experiment.cs
src/Microsoft.ComponentDetection.Orchestrator/Experiments/ExperimentService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Experiments/ExperimentServiceTests.cs

The logging in `ExperimentService` was broken as it contained two identical `{Count}` parameters.
In addition, if the results of an experiment are completely empty (_i.e._ no components detected in the control group and experiment group), we should skip processing as an empty diff is indicative of a perfect detector.
Lastly, certain detectors running invalidates the experiment results. For instance, in the NPM Lockfile v3 experiment, if the lockfile v2 detector runs, we would be comparing the `NpmComponentDetector` (which would detect _N_ components), to the `NpmLockfile3Detector` (which would detect _**0**_ components). So, the experiment is tainted and we should not process it.

fix(experiment): don't process if empty or tainted

---

src/Microsoft.ComponentDetection.Orchestrator/Experiments/ExperimentService.cs
src/Microsoft.ComponentDetection.Orchestrator/Experiments/Models/ExperimentDiff.cs

Refactors the `ExperimentDiff` to be immutable, so we can safely process the experiments in parallel. 🦀 
The two processors at the moment, one to write to disk, and a future one to upload to Azure Blob Storage for internal customers, should run in parallel to not slow down CD.

perf: process experiments in parallel

---

.github/workflows/build.yml
.github/workflows/snapshot-publish.yml
.github/workflows/snapshot-verify.yml

Uses [actions/cache](https://github.com/actions/cache) to cache NuGet packages. Should speed up CI.
This is similar to other .NET projects CI workflow:
See Polly's CI: https://github.com/App-vNext/Polly/blob/a1ef1bb54c9aabd95b684d4c5cfde6dfc693a5ae/.github/workflows/build.yml#L37-L49
Omitted caching the release workflow, as we should rebuild from scratch when releasing.

ci: cache NuGet packages

---

src/Microsoft.ComponentDetection.Orchestrator/Experiments/ExperimentService.cs

We remove all and then iterate the experiments in a non thread-safe manner. Switch to a concurrent dictionary.

fix: filter experiments thread-safely

---

.github/workflows/smoke-test.yml

This PR adds a new GitHub Actions workflow for running smoke tests on various repositories using different package managers. The smoke tests will be executed on every push, pull request, and daily at midnight.
The new workflow is named "Smoke Tests" and consists of the following steps:
1. Checkout Component Detection.
2. Setup .NET environment.
3. Setup NuGet cache.
4. Install Apache Ivy.
5. Checkout the smoke test repository.
6. Run the smoke test, executing the component detection tool 10 times.
The workflow uses a matrix strategy to run the tests across various repositories using different package managers, including:
- CocoaPods: [realm/realm-swift](https://github.com/realm/realm-swift)
- Gradle: [microsoft/ApplicationInsights-Java](https://github.com/microsoft/ApplicationInsights-Java …

ci: add smoke test

---

src/Microsoft.ComponentDetection.Orchestrator/Experiments/Models/ExperimentResults.cs

Uses the `ConcurrentDictionary` trick to make a thread safe hash set. We use an `ExperimentComponentComparer` which filters by the component Id.
This prevents duplicate ids.

fix: make `ExperimentResults` thread safe

---

docs/environment-variables.md

This was updated to 4096 in https://github.com/microsoft/component-detection/pull/385
https://github.com/microsoft/component-detection/blob/804182a508109a36e72f7ecced7d74452c96e405/src/Microsoft.ComponentDetection.Detectors/pip/IPyPiClient.cs#L33

docs: correct pip default cache enties

---

src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DetectorProcessingServiceTests.cs

Reverts microsoft/component-detection#533
Now that the components are unique and there are no multithreading issue, should be good to go! 🤞 😓

fix; reenable experiments

---

.github/workflows/smoke-test.yml

The NuGet smoke test didn't restore NuGet packages, resulting in no packages being detected.
We switched to ~https://github.com/jellyfin/jellyfin~ https://github.com/Radarr/Radarr as Powershell requires .NET 8.

ci(smoke-test): restore nuget packages

---

Directory.Packages.props
src/Microsoft.ComponentDetection.Contracts/Microsoft.ComponentDetection.Contracts.csproj

This is required as our contracts package targets `netstandard2.0`
Part of #231

chore(deps): add dependency on `System.Text.Json` to `Microsoft.ComponentDetection.Contracts`

---

src/Microsoft.ComponentDetection.Orchestrator/Experiments/Configs/NpmLockfile3Experiment.cs

We don't want to record experiment data if the lockfile v2 detector is running 😓

fix(experiments): should record condition

---

src/Microsoft.ComponentDetection.Orchestrator/Experiments/Configs/NpmLockfile3Experiment.cs

We want to only capture experiments on repositories that are purely just NPM or NPM lockfile version 3. Any other NPM replacement (like yarn, pnpm, etc.) are noise to the experiment data, as these package managers also restore NPM dependencies, including their `package.json`, which gets detected by the `NpmComponentDetector`.
I've verified that there are repositories that follow this criteria by checking our telemetry.

fix(experiments): tighten NPM lockfile v3 condition

---

src/Microsoft.ComponentDetection.Common/FileWritingService.cs
src/Microsoft.ComponentDetection.Common/IFileWritingService.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/BcdeScanCommandService.cs
test/Microsoft.ComponentDetection.Common.Tests/FileWritingServiceTests.cs

As we're unable to move to `System.Text.Json` with the feature set that is available in .NET 6 (See #231 for more information), this PR optimizes our use of `Newtonsoft.Json` by using streaming methods for our most allocation-heavy methods where possible.
In tests against real world repositories this dropped memory usage by up to 37% when writing the manifest JSON.
There is also some refactoring and tech debt cleanup in tests and documentation.

feat: use `Newtonsoft.Json` streaming methods

---

src/Microsoft.ComponentDetection.Orchestrator/Experiments/ExperimentService.cs
src/Microsoft.ComponentDetection.Orchestrator/Experiments/IExperimentService.cs
src/Microsoft.ComponentDetection.Orchestrator/Experiments/Models/ExperimentComponent.cs
src/Microsoft.ComponentDetection.Orchestrator/Experiments/Models/ExperimentResults.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/GraphTranslation/DefaultGraphTranslationService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Experiments/ExperimentDiffTests.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Experiments/ExperimentResultsTests.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Experiments/ExperimentServiceTests.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Experiments/ExperimentTestUtils.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DetectorProcessingServiceTests.cs

`DetectedComponent` has the metadata such as whether the component is a development dependency, and the root components, but this data is not actually set.
Instead, detectors create `DetectedComponent`s with the `TypedComponent`, and the metadata is passed into `ComponentRecorder` which then appends the component to the graph with proper metadata.
This switches experiments from using `DetectedComponent` to `ScannedComponent` by using the `IGraphTranslationService` to parse the data from the `ComponentRecorder`.
Fixes #611

fix(experiments): properly record metadata

---

src/Microsoft.ComponentDetection.Detectors/pip/IPyPiClient.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PyPiClientTests.cs

This will add 2 `User-Agent` headers to all requests to PyPI:
- `ComponentDetection/{version}` (A product identifier)
- `(+https://github.com/microsoft/component-detection)` (A comment)
See MDN documentation for more details on this header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

fix: add `user-agent` headers to requests with pypiclient

---

Directory.Packages.props
test/Microsoft.ComponentDetection.Contracts.Tests/DetectedComponentTests.cs
test/Microsoft.ComponentDetection.Contracts.Tests/Microsoft.ComponentDetection.Contracts.Tests.csproj
test/Microsoft.ComponentDetection.Orchestrator.Tests/Experiments/ExperimentDiffTests.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Microsoft.ComponentDetection.Orchestrator.Tests.csproj
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/BcdeScanExecutionServiceTests.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DetectorProcessingServiceTests.cs

This adds `FluentAnalyzers.Assertions` and fixes warnings in `Microsoft.ComponentDetection.Contracts.Tests` and `Microsoft.ComponentDetection.Orchestrator.Tests`
Related to #633

refactor: add `FluentAssertions.Analyzers` and fix some warnings

---

docs/schema/manifest.schema.json

Adds a JSON Schema for the Manifest format. Generated with [`JSON.NET Schema`](https://www.newtonsoft.com/jsonschema/help/html/Introduction.htm)
```csharp
using Microsoft.ComponentDetection.Contracts.BcdeModels;
using Newtonsoft.Json.Schema.Generation;
var generator = new JSchemaGenerator();
var schema = generator.Generate(typeof(ScanResult));
// Add meta schema
schema.ExtensionData.Add("$schema", "http://json-schema.org/draft-07/schema#");
Console.WriteLine(schema.ToString());
```
Part of #570

feat: add json schema for manifest

---

src/Microsoft.ComponentDetection.Detectors/conda/CondaDependencyResolver.cs
src/Microsoft.ComponentDetection.Detectors/conda/CondaLockComponentDetector.cs

So far, python components have only been created for packages which are managed by pip. However, 90% of the conda packages are python packages, even though they are managed by conda instead of pip. 
This PR is improving the detection by adding support for detecting python packages which are managed by conda.

Improve the detection of pip components in the CondaLockDetector

---

.github/workflows/smoke-test.yml

Every PR runs two copies of the smoke test, one because a user pushed to their local branch, and another from the pull request trigger.
I think it's best to leave `push` and `pull_request` triggers, as I'm not sure if `push` will trigger on a PR from a fork.

ci: limit smoke tests push trigger to main

---

src/Microsoft.ComponentDetection.Orchestrator/Experiments/ExperimentService.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/GraphTranslation/DefaultGraphTranslationService.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/GraphTranslation/IGraphTranslationService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Experiments/ExperimentServiceTests.cs

Fixes experiments overwriting file locations and corrupting them with bad relative paths.

fix(experiments): don't overwrite file locations

---

.git-blame-ignore-revs

git and GitHub don't accept the file with the leading UTF8 BOM.

chore: re-encode git-blame-ignore-revs file to utf8 without bom

---

.github/workflows/sync-issues.yml

Changes include:
- Unset `ado_bypassrules` as we don't have bypass rules permissions
- Correctly set states for tasks
- Unset `log_leve` as 100 is the default level

chore: correct settings for work item sync workflow

---

.github/workflows/smoke-test.yml
.github/workflows/snapshot-publish.yml
.github/workflows/snapshot-verify.yml

CI needs to run detector experiments to verify it works.
Also reformatted the workflows.

ci: enable detector experiments

---

test/Microsoft.ComponentDetection.Common.Tests/BaseDetectionTelemetryRecordTests.cs
test/Microsoft.ComponentDetection.Common.Tests/CommandLineInvocationServiceTests.cs
test/Microsoft.ComponentDetection.Common.Tests/ComponentStreamEnumerableTests.cs
test/Microsoft.ComponentDetection.Common.Tests/DependencyGraphTests.cs
test/Microsoft.ComponentDetection.Common.Tests/DockerServiceTests.cs
test/Microsoft.ComponentDetection.Common.Tests/EnvironmentVariableServiceTests.cs
test/Microsoft.ComponentDetection.Common.Tests/FileEnumerationTests.cs
test/Microsoft.ComponentDetection.Common.Tests/Microsoft.ComponentDetection.Common.Tests.csproj

Cleans up some tests in `Microsoft.ComponentDetection.Common.Tests` to use `FluentAssertions`.
Part of #633

refactor: use `FluentAssertions.Analyzers` for Common tests

---

Directory.Packages.props

Reverts microsoft/component-detection#698
Spyware. See https://github.com/moq/moq/issues/1372

Revert "chore(deps): update dependency moq to v4.20.1"

---

docs/detectors/conan.md
src/Microsoft.ComponentDetection.Contracts/BcdeModels/TypedComponentConverter.cs
src/Microsoft.ComponentDetection.Contracts/TypedComponent/ComponentType.cs
src/Microsoft.ComponentDetection.Contracts/TypedComponent/ConanComponent.cs
src/Microsoft.ComponentDetection.Detectors/conan/ConanLockComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/conan/Contracts/ConanLock.cs
src/Microsoft.ComponentDetection.Detectors/conan/Contracts/ConanLockGraph.cs
src/Microsoft.ComponentDetection.Detectors/conan/Contracts/ConanLockNode.cs
src/Microsoft.ComponentDetection.Orchestrator/Extensions/ServiceCollectionExtensions.cs
test/Microsoft.ComponentDetection.Contracts.Tests/TypedComponentSerializationTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/ConanLockComponentDetectorTests.cs
test/Microsoft.ComponentDetection.VerificationTests/resources/VerificationTest.ps1
test/Microsoft.ComponentDetection.VerificationTests/resources/conan/conanPythonFile/conan.lock
test/Microsoft.ComponentDetection.VerificationTests/resources/conan/conanPythonFile/conanfile.py
test/Microsoft.ComponentDetection.VerificationTests/resources/conan/conanTextFile/conan.lock
test/Microsoft.ComponentDetection.VerificationTests/resources/conan/conanTextFile/conanfile.txt

This PR adds support for identifying components from conan.lock files created by conan package manager. 
Doesn't require conan package manager to have been installed.

Feature: Add conan detector that parses conan.lock files of conan package manager version 1.x

---

src/Microsoft.ComponentDetection.Detectors/rust/RustCrateDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/RustCrateDetectorTests.cs

Remove Rust detector exception for a Source dependency having a dependency on a non-Source dependency.
This is seen in the Rust project's lockfile: https://github.com/rust-lang/rust/blob/1554942cdc0099e081d5cd673d45f8a09cfd0eb0/Cargo.lock#L6 where `rustc-std-workspace-alloc` has no `source`, dispite being a dependency of `addr2line` (which does have a `source`).

Fix Rust detector exception for non-source dependency

---

docs/detectors/go.md

Fixing a typo where we recommended `go mod tidy` for the default strategy rather than the fallback strategy. The default strategy doesn't use `go.sum` files.

docs(go): Go strategy doc fix

---

README.md
docs/detector-arguments.md

Adding instructions to specify the ComponentDetection project with `dotnet run` in the README. 
`-p` is also deprecated in favor of `--project`.

docs(readme): Fix README dotnet run instructions

---

src/Microsoft.ComponentDetection.Common/Telemetry/Records/GoGraphTelemetryRecord.cs
src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs

Extending the `GoGraph` telemetry object to report on when and why we are using the Go fallback detection strategy so that we may assess strategy distribution and reasoning for fallback strategy use.

feat: record telemetry on Go fallback detection strategy

---

src/Microsoft.ComponentDetection.Detectors/nuget/NuGetComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NuGetComponentDetectorTests.cs

fix(nuget): null ref when parsing `paket.lock`

---

.github/workflows/release.yml

We cannot rerun our release pipeline after our Azure Artifacts PAT expired since this step will fail as we already uploaded assets.

ci(release): ignore asset upload failures

---

src/Microsoft.ComponentDetection.Detectors/nuget/NuGetPackagesConfigDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/nuget/NuGetPackagesConfigDetectorTests.cs

This prevents issues for those that have configured error logs in CI to break builds. Really, we should continue, and a single invalid `packages.config` file shouldn't break a build.
Also added documentation and a new test.

Downgrade invalid `packages.config` files from an error to warning

---

src/Microsoft.ComponentDetection.Common/Telemetry/Records/GoGraphTelemetryRecord.cs
src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs

**Changes**
- Create telemetry object after project roots command succeeds to avoid empty telemetry objects
- Remove `WasGoCliNotFound` as it was the exact inverse of `IsGoInstalled`
- Add `DidGoCliCommandFail` and `GoCliCommandError` to track `go list` failures

feat(go): break down telemetry on go cli command failures

---

src/Microsoft.ComponentDetection.Common/Telemetry/Records/GoGraphTelemetryRecord.cs
src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs

Records the go version stored in `go.mod` for telemetry.
Example `go.mod` file, where go > 1.17:
```
module example/web-service-gin
go 1.18
require github.com/gin-gonic/gin v1.9.1
require (
github.com/bytedance/sonic v1.9.1 // indirect
github.com/chenzhuoyu/base64x v0.0.0-20221115062448-fe3a3abad311 // indirect
github.com/gabriel-vasile/mimetype v1.4.2 // indirect
github.com/gin-contrib/sse v0.1.0 // indirect
github.com/go-playground/locales v0.14.1 // indirect
github.com/go-playground/universal-translator v0.18.1 // indirect
github.com/go-playground/validator/v10 v10.14.0 // indirect
github.com/goccy/go-json v0.10.2 // indirect
github.com/json-iterator/go v1.1.12 // indirect
github.com/klauspost/cpuid/v2 v2.2.4 // indirect
github.com/leodido/go-urn v1.2.4 // indirect …
```

feat(go): record version in `go.mod`

---

.github/workflows/smoke-test.yml
.github/workflows/snapshot-publish.yml
.github/workflows/snapshot-verify.yml

It seems that Apache Ivy 2.5.1 was removed today, and 2.5.2 was recently released last week.
The old link to v2.5.1 is dead.

ci: update ivy to v2.5.2

---

.github/workflows/build.yml
.github/workflows/smoke-test.yml
.github/workflows/snapshot-publish.yml
.github/workflows/snapshot-verify.yml

This is causing problems for some builds, and the caching doesn't yield results.

ci: remove nuget caching

---

src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/GoComponentDetectorTests.cs

This PR adds support for `go.mod` files that were created with go versions >= 1.17.
Since go 1.17, `go.mod` files now contain all transitive dependencies[^1], _in a separate requires_ section. This means that we do not have to parse the `go.sum` file for dependencies, which can contain dependencies that aren't actually used.
Additionally, the `go.mod` file can require dependencies without a section, like:
```
require github.com/go-sql-driver/mysql v1.7.1 // indirect
```
We also now support two `go.mod` `require` sections:
```
module microsoft/component-detection
go 1.18
require (
github.com/go-sql-driver/mysql v1.7.1
rsc.io/quote v1.5.2
)
require (
golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c // indirect
rsc.io/sampler v1.3.0 // indirect
)
```
Closes #737 
[^1]: …

feat(go): better `go.mod` scanning for go >= 1.17

---

.github/workflows/build.yml

We have some tests that are not run on windows and vice verse. We should be running those tests in CI.

ci(build): build on windows and linux

---

src/Microsoft.ComponentDetection.Contracts/TypedComponent/SpdxPackageComponent.cs
src/Microsoft.ComponentDetection.Detectors/spdx/Contracts/CreationInfo.cs
src/Microsoft.ComponentDetection.Detectors/spdx/Contracts/SpdxExternalRefs.cs
src/Microsoft.ComponentDetection.Detectors/spdx/Contracts/SpdxFileData.cs
src/Microsoft.ComponentDetection.Detectors/spdx/Contracts/SpdxPackage.cs
src/Microsoft.ComponentDetection.Detectors/spdx/Spdx22ComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/SPDX22ComponentDetectorTests.cs

right now, component detection was correctly detecting the SBOM file(s) if any present in the project folder,  but it was not including packages information from already present SBOM file to newly generated file.
example -> Project A reference Project B 
Steps 
1) Generate SBOM for Project B  and include SBOM file in Project A 
2) Generate SBOM for Project A
Expected Result -> SBOM file generated for project A should include packages information from SBOM file generated for Project B
Actual Result -> SBOM file is identified but the package information is not considered.

Added spdx package component information from SPDX file

---

.github/workflows/build.yml

Reverts microsoft/component-detection#784
This breaks code coverage uploading, v4 is currently beta: https://github.com/codecov/codecov-action#v4-beta-release

revert:"chore(deps): update codecov/codecov-action action to v4"

---

Directory.Packages.props

We cannot release a version of CD with a pre-release version of a dependency or MinVer will break the build.

chore(deps): downgrade `Spectre.Console` to v0.47.0

---

src/Microsoft.ComponentDetection.Orchestrator/Commands/ScanSettings.cs

This is incorrect, it's supposed to be comma-delimited.

fix: `--IgnoreDirectories` delimited by commas

---

src/Microsoft.ComponentDetection.Orchestrator/Commands/BaseSettings.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Commands/BaseSettingsTests.cs

This used to be validated in the Orchestrator

fix: validate `--Output`

---

src/Microsoft.ComponentDetection.Orchestrator/Experiments/Configs/IExperimentConfiguration.cs
src/Microsoft.ComponentDetection.Orchestrator/Experiments/Configs/RustCliDetectorExperiment.cs
src/Microsoft.ComponentDetection.Orchestrator/Experiments/ExperimentService.cs
src/Microsoft.ComponentDetection.Orchestrator/Experiments/IExperimentService.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Experiments/ExperimentServiceTests.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DetectorProcessingServiceTests.cs

Adds a new `InitAsync` method to configurations that allows them to do some setup. Useful for the `RustCliExperiment` as we only want to record this experiment if `cargo` is available.
This had to be made into a separate method as the experiment methods aren't async, and the `CommandLineInvocationService` is async.

feat(experiments): record rust cli if `cargo` exists

---

src/Microsoft.ComponentDetection.Contracts/BcdeModels/ScanResult.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/ScanExecutionService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/BcdeScanExecutionServiceTests.cs

Readded changes to populate disabled detectors list and added some unit tests. Also modified `ScanResult` contract to help with the unit tests.

PR to populate disable detectors list

---

docs/detectors/go.md

Docs on how to ensure that the go default strategy runs successfully.

docs(go): add go fallback strategy troubleshooting guide

---

test/Microsoft.ComponentDetection.Orchestrator.Tests/Experiments/ExperimentConfigTests.cs

tests: verify `IExperimentConfiguration`s

---

.github/codecov.yml

Ignore 1% differences in coverage and round down with a precision of 1.

chore: add `codecov.yml`

---

src/Microsoft.ComponentDetection/Program.cs

Based on these threads [Stack Overflow](https://stackoverflow.com/questions/63199414/asp-net-core-3-1-httpmessagehandler-cleanup-cycle), [Github](https://github.com/aspnet/HttpClientFactory/issues/165), It seems the multiple cleanup messages are default behavior as it waits to clean up the message handler resources. The suggested thing to do is hide the messages in the logs if we don't want to see them.

Fix to hide Http MessageHandler cleanup messages

---

src/Microsoft.ComponentDetection.Detectors/pip/SimplePipComponentDetector.cs

move simple pip to default off

move simple pip to default off

---

src/Microsoft.ComponentDetection.Contracts/TypedComponent/VcpkgComponent.cs

Added GitRepositoryOwner and GitRepositoryName to prevent fuzzy matching

Add Properties VCPKG

---

Directory.Packages.props
src/Microsoft.ComponentDetection.Common/Microsoft.ComponentDetection.Common.csproj

It's not used anywhere in the codebase.

Remove `Microsoft.AspNet.WebApi.Client`

---

src/Microsoft.ComponentDetection.Contracts/TypedComponent/VcpkgComponent.cs
src/Microsoft.ComponentDetection.Detectors/vcpkg/VcpkgComponentDetector.cs

Removing VCPKG Properties because they are not first-class metadata fields of VCPKG.

Removing VCPKG Properties

---

src/Microsoft.ComponentDetection.Detectors/rust/RustCliDetector.cs

fix(rust): don't mark build deps as dev deps

---

src/Microsoft.ComponentDetection.Detectors/rust/RustCliDetector.cs

Issue #894 suggests using the `--all-features` flag for `cargo metadata` to avoid potential false negatives from dependencies that aren't used by default.
This PR adds that flag to the `cargo metadata` command line in the Rust CLI detector.

Add --all-features per issue #894

---

src/Microsoft.ComponentDetection.Orchestrator/Commands/ScanSettings.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs

Fixes #900
This PR just adds a parameter to `ScanCommandSettings`: `--NoSummary` to completely disable the rendering/logging of the detection summary.
This is useful when an application directly controls the execution of the `component-detection`. Displaying the detection summary directly on the standard output can interfere with the main application's own output.
The manifest already provides all the necessary information for the host application to display it's own status.
I did not add a test for this super simple feature. Because this is an implementation detail of the `DetectorProcessingService` that doesn't seem easily testable with the available mocks. 
Thanks!

Add a parameter to disable the summary display

---

docs/detector-arguments.md

Following changes in https://github.com/microsoft/component-detection/pull/917 for `--NoSummary`
I also documented `--PrintManifest` which was missing.
cc @annaowens

Update documentation for detector arguments

---

CONTRIBUTING.md
src/Microsoft.ComponentDetection.Detectors/yarn/Parsers/IYarnBlockFile.cs
src/Microsoft.ComponentDetection.Detectors/yarn/Parsers/YarnBlockFile.cs
src/Microsoft.ComponentDetection.Detectors/yarn/Parsers/YarnLockParser.cs
src/Microsoft.ComponentDetection.Detectors/yarn/YarnLockComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/yarn/YarnLockVersion.cs
test/Microsoft.ComponentDetection.Detectors.Tests/Yarn/YarnBerryTypeConverterTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/YarnBlockFileTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/YarnParserTests.cs

Yarn v1 does not list local workspace projects in the `yarn.lock` file, but Yarn "berry" (>= v2) does. As a result, there is a difference in behavior in the component detection between the two versions. On very large mono-repo projects (such as Outlook's main client repository), this change combined with the very repetitive/uncompressed nature of the resulting scan report JSON can balloon to an unmanageable size (>80x increase in Outlook's case).
This change fixes code looking for "resolved" in Yarn berry lockfiles to look for "resolution" instead (the new entry name). Additionally, it simply skips detection for local workspace projects to maintain parity with v1 detection (these projects are still detected by the NPM detector).

Skip detection of workspace projects in Yarn detector

---

src/Microsoft.ComponentDetection.Detectors/pip/IPyPiClient.cs
src/Microsoft.ComponentDetection.Detectors/pip/PythonVersion.cs

Fixes #862 where multiple threads are attempting to parse the version RegEx at once and `.Add` failing due to duplicates.

Resolve Pip TryAdd exception on duplicates

---

src/Microsoft.ComponentDetection.Detectors/npm/NpmLockfile3Detector.cs

Promote NPM Lockfile v3 detector to run by default

---

README.md

The extra `tag` was making GitHub unhappy :).

Fix link to the latest release

---

src/Microsoft.ComponentDetection.Detectors/pip/IPyPiClient.cs
src/Microsoft.ComponentDetection.Detectors/pip/PythonResolver.cs
src/Microsoft.ComponentDetection.Detectors/pip/PythonResolverBase.cs
src/Microsoft.ComponentDetection.Detectors/pip/SimplePythonResolver.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PipResolverTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/SimplePythonResolverTests.cs

In the Python detectors, there are a few exceptions which are currently unhandled, leading to failures in detection which are not well presented to the user. Add some additional handling when this occurs so users have a good idea of why the error occurred and can investigate themselves to see if detection or their requirements need changes. Related issue #928 
**First case:**
Python package has multiple dependencies specified with the same package name, but differing version constraints. An exception will be hit because of the `ToDictionary` call which expects distinct values.
```
System.ArgumentException: An item with the same key has already been added. Key: portalocker
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at …
```

Make Python detection more resilient to unexpected failure cases

---

src/Microsoft.ComponentDetection.Detectors/linux/Contracts/SyftOutput.cs
src/Microsoft.ComponentDetection.Detectors/linux/LinuxScanner.cs
test/Microsoft.ComponentDetection.Detectors.Tests/LinuxScannerTests.cs

It's been a while since this has been updated. Unfortunately, I no longer have access to the Azure Container Registry, so someone from the team will need to manually run:
```
az login
az acr login --name governancecontainerregistry
skopeo copy --all docker://docker.io/anchore/syft:v0.100.0 docker://governancecontainerregistry.azurecr.io/syft:v0.100.0
```
The full instructions are available [here][1]
[1]: https://github.com/microsoft/component-detection/blob/main/docs/update-syft.md

Bump Syft from `0.74.0` to `0.100.0`

---

src/Microsoft.ComponentDetection.Contracts/BcdeModels/ScannedComponent.cs
src/Microsoft.ComponentDetection.Contracts/DetectedComponent.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/GraphTranslation/DefaultGraphTranslationService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/BcdeScanExecutionServiceTests.cs

This pr is required by https://github.com/microsoft/sbom-tool/pull/457 which display Hierarchy of package dependency in relatrionship section of SBOM

Get ancestor for displaying dependency tree in relationships

---

docs/detectors/poetry.md
src/Microsoft.ComponentDetection.Detectors/poetry/Contracts/PoetryPackage.cs
src/Microsoft.ComponentDetection.Detectors/poetry/PoetryComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PoetryComponentDetectorTests.cs

As of poetry 1.5.0 this field is no longer recorded in lockfiles: https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md#150---2023-05-19
This causes the poetry detector to misclassify normal dependencies as dev dependencies, due to the existing logic of classifying dependencies as normal if and only if the category field is present and "main".
This follows the approach of https://github.com/microsoft/component-detection/pull/117, which conservatively adds all dependencies from the lockfile as normal dependencies lest dev dependencies be misclassified inadvertently.

remove category usage from the poetry detector

---

src/Microsoft.ComponentDetection.Detectors/pip/PipComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/pip/PythonResolver.cs
src/Microsoft.ComponentDetection.Detectors/pip/SimplePipComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/pip/SimplePythonResolver.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PipResolverTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/SimplePythonResolverTests.cs

When an invalid version specification is returned from PyPi (i.e. `Requires-Dist: c (>dev)`) the current implementation of Python resolvers both throw the exception all the way out, leading to a complete failure of Python graph creation. In this case we should log the warning and continue executing to get as many dependencies as possible.

Catch version spec failures in Python detection

---

src/Microsoft.ComponentDetection.Detectors/pip/PythonVersionUtilities.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PythonVersionTests.cs

This PR addresses issue #833 . The root cause of the problem was our handling of versions, which included spaces. When creating a Python version from a string, we encountered an issue: the version passed as a parameter (including spaces) did not align with the value extracted from the regular expression (regex). The PR rectified this inconsistency, ensuring consistent version handling.

Ignore leading and trailing spaces on versions

---

src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetectorWithRoots.cs
src/Microsoft.ComponentDetection.Detectors/npm/NpmLockfile3Detector.cs
src/Microsoft.ComponentDetection.Detectors/npm/NpmLockfileDetectorBase.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmDetectorWithRootsTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmLockfile3DetectorTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmTestUtilities.cs
test/Microsoft.ComponentDetection.VerificationTests/resources/npm/lockfile3/package-lock.json
test/Microsoft.ComponentDetection.VerificationTests/resources/npm/lockfile3/package.json

Currently `optionalDependencies` in npm lockfiles are not detected by  `NpmLockFile3Detector` and `NpmDetectorWithRoots`. This is fixed by this PR. 
- `optionalDependencies` are now registered same as the regular dependencies, "optional" status is not reflected in Detection.
- added unit test for optional Dependencies detection.
- Noticed that dev Dependency unit tests were missing, added those as well.
- Locally verified that optional Dependencies are registered in the scan manifest. 
- Added verification test resources for lockfile 3

Added optional dependency detection for npm lockfiles (version 2 and 3)

---

src/Microsoft.ComponentDetection.Detectors/maven/IMavenStyleDependencyGraphParserService.cs
src/Microsoft.ComponentDetection.Detectors/maven/MavenCommandService.cs
src/Microsoft.ComponentDetection.Detectors/maven/MavenParsingUtilities.cs
src/Microsoft.ComponentDetection.Detectors/maven/MavenStyleDependencyGraphParser.cs
src/Microsoft.ComponentDetection.Detectors/maven/MavenStyleDependencyGraphParserService.cs
src/Microsoft.ComponentDetection.Detectors/maven/MvnCliComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/MavenParsingUtilitiesTests.cs

Currently maven detector is failing for invalid `<scope>` in maven dependency file. However, these dependencies are valid as per maven cli and evaluated as "Compile". Component Detector matches the maven's behavior to evaluate these "invalid" scope as "Compile"
#858 
- local testing
- updated unit test for invalid dependency

Evaluating invalid maven scope as "Compile"

---

src/Microsoft.ComponentDetection.Common/FastDirectoryWalkerFactory.cs
src/Microsoft.ComponentDetection.Detectors/pip/IPyPiClient.cs
src/Microsoft.ComponentDetection.Detectors/pip/IPythonCommandService.cs
src/Microsoft.ComponentDetection.Detectors/pip/PipComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/pip/PythonCommandService.cs
src/Microsoft.ComponentDetection.Detectors/pip/SimplePipComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/pip/SimplePythonResolver.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PyPiClientTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PythonCommandServiceTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/SimplePythonResolverTests.cs

This PR is to fix issue #32 
Ex of requirement.txt file
```
numpy==1.23.0rc3
xyz01==0.2
```
Dependency graph results

Support for release candidate versions python detector

---

src/Microsoft.ComponentDetection.Contracts/TypedComponent/VcpkgComponent.cs
test/Microsoft.ComponentDetection.Detectors.Tests/VcpkgComponentDetectorTests.cs

Updating slightly the component ID to include the origin of the VCPKG package for increased accuracy, as packages can be consumed from anywhere. This component type behaves similarly to Git components for some of their resources.

Update VCPKG component identifier in detector

---

src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/go/GoComponentWithReplaceDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/GoComponentWithReplaceDetectorTests.cs

Adding replacement module for the GO CLI scan not just fallback scan 
#122

Go CLI Replacement

---

src/Microsoft.ComponentDetection.Detectors/ivy/IvyDetector.cs

IvyDetector creates files in a folder named "ComponentDetection_Ivy" in the temporary folder.
However if multiple detectors run in parallel, it brings a race condition when detectors manipulate files in the same folder.
Solution: Use random name for IvyDetector working folder.

Use a random name for working folder for IvyDetector

---

src/Microsoft.ComponentDetection.Contracts/TypedComponent/CargoComponent.cs
src/Microsoft.ComponentDetection.Detectors/rust/RustCliDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/RustCliDetectorTests.cs

Allows users to manually override rustCLI detector by setting an environment variable DisableRustCliScan=True
Updates cargo metadata output processing to adhere to changes introduced that make the output follow the PkgId Spec: https://doc.rust-lang.org/cargo/reference/pkgid-spec.html
Changes to the metadata output were introduced in 1.77: https://github.com/rust-lang/cargo/pull/12914

Update RustCli Parsing to process pkgId, and introduce manual override

---

.github/workflows/smoke-test.yml
docs/detectors/pip.md
src/Microsoft.ComponentDetection.Detectors/pip/PipCommandService.cs
src/Microsoft.ComponentDetection.Detectors/pip/PipReportComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PipCommandServiceTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PipReportComponentDetectorTests.cs

Slightly change error handling in the pip report detector to avoid attempting to parse failed reports. Add some new docs and update smoke tests to avoid rate limiting failures.

Small updates to PipReport detector

---

docs/detectors/pip.md
src/Microsoft.ComponentDetection.Detectors/pip/IPyPiClient.cs
src/Microsoft.ComponentDetection.Detectors/pip/SimplePypiClient.cs

Increase Python cache window used for sliding expiration of PyPi responses so cache hits are more likely.

Increase Python cache window

---

src/Microsoft.ComponentDetection.Common/PathUtilityService.cs
src/Microsoft.ComponentDetection.Contracts/IPathUtilityService.cs
test/Microsoft.ComponentDetection.Common.Tests/PathUtilityServiceTests.cs

When running the Pip detection for setup.py files, there were extra unicode characters being added to the normalized path strings. This will fix that issue by normalizing to `/` which is valid on both Unix and Windows.

Update NormalizePath to handle Windows correctly

---

src/Microsoft.ComponentDetection.Common/CommandLineInvocationService.cs
src/Microsoft.ComponentDetection.Common/Utilities/StringUtilities.cs
src/Microsoft.ComponentDetection.Detectors/pip/PipCommandService.cs
test/Microsoft.ComponentDetection.Common.Tests/StringUtilitiesTests.cs

User reported PyPI CLI commands service was logging in telemetry file the credentials set in `PIP_INDEX_URL` environment variable. Since this variable is set dynamically by users we can't control what goes into it, but we still want to keep track in telemetry of the actual command output.
We can sanitize the strings used in CLI before logging them, so we don't log any sensitive information. We can also add a 5 second timeout in case we see an unexpected command.

Simple sanitization in strings used in CLI before logging

---

src/Microsoft.ComponentDetection.Detectors/gradle/GradleComponentDetector.cs

Update Gradle parsing to reduce logging calls to IsDevDependencyByLockfile since it only needs to be calculated once per file.

Update Gradle parsing to reduce logging calls

---

src/Microsoft.ComponentDetection.Common/DockerService.cs
src/Microsoft.ComponentDetection.Common/Utilities/StringUtilities.cs
test/Microsoft.ComponentDetection.Common.Tests/DockerServiceTests.cs
test/Microsoft.ComponentDetection.Common.Tests/Microsoft.ComponentDetection.Common.Tests.csproj
test/Microsoft.ComponentDetection.Common.Tests/StringUtilitiesTests.cs

We spotted some ephemeral credentials in our telemetry due to syft being executed in a container and returning all/most of its environment variables.
Sanitize confidential information placed in URLs within env vars passed to Syft.

Sanitize Docker environment vars in logs

---

src/Microsoft.ComponentDetection.Common/DockerService.cs

There is another Docker event logging the docker image response which can include environment variables. We need to sanitize them to prevent logging creds pointing to feeds.

Sanitize another Docker telemetry event

---

src/Microsoft.ComponentDetection.Common/Telemetry/Records/PipReportSkipTelemetryRecord.cs
src/Microsoft.ComponentDetection.Detectors/pip/PipReportComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PipReportComponentDetectorTests.cs

Pip report causes customers to have their runs timeout. To immediately unblock customers, this adds the ability to not run pipreport detection. Investigating root cause in meantime

Add env var that allows customers to skip pip report

---

src/Microsoft.ComponentDetection.Common/CommandLineInvocationService.cs
src/Microsoft.ComponentDetection.Contracts/FileComponentDetector.cs
src/Microsoft.ComponentDetection.Contracts/ScanRequest.cs
src/Microsoft.ComponentDetection.Orchestrator/Commands/ScanSettings.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Commands/ScanSettingsTests.cs
test/Microsoft.ComponentDetection.VerificationTests/resources/pip/parallel/parallel-test-1/requirements.txt
test/Microsoft.ComponentDetection.VerificationTests/resources/pip/parallel/parallel-test-2/requirements.txt
test/Microsoft.ComponentDetection.VerificationTests/resources/pip/parallel/parallel-test-3/requirements.txt
test/Microsoft.ComponentDetection.VerificationTests/resources/pip/parallel/parallel-test-4/requirements.txt
test/Microsoft.ComponentDetection.VerificationTests/resources/pip/parallel/parallel-test-5/requirements.txt

Adds some configurable parallelism to a single detector, e.g. within PipReport. 
Added some simple pip reports that take 3-5 seconds to generate.
Running with the `MaxDetectionThreads` set to 1:
Running without the `MaxDetectionThreads` (default of 10):
Finally, with `MaxDetectionThreads` set to 2:
Scan log from the 2 parallel threads is also interesting since you can see that 2 pip reports are triggered at the same time and the next set is triggered once these finish:
[GovCompDisc_Log_20240612152920140_41928.log](https://github.com/user-attachments/files/15811613/GovCompDisc_Log_20240612152920140_41928.log)

Enable parallelism by detector

---

docs/detectors/pip.md
src/Microsoft.ComponentDetection.Detectors/pip/Contracts/PipDependencySpecification.cs
src/Microsoft.ComponentDetection.Detectors/pip/PipReportComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/pip/PythonVersionUtilities.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PipReportComponentDetectorTests.cs
test/Microsoft.ComponentDetection.VerificationTests/resources/pip/fallback/requirements.txt

PipReportOverrideBehavior that allows us to skip pip report or fallback to scanning source files directly without reaching out to remote package repos for the full dependency graph.

PipReport option to fallback and parse roots from source

---

.github/workflows/release.yml

No longer can use this release step, as it requires a PAT auth method that is no longer supported. 
We do not need this step, as we have the public feed that this gets pushed to as an upstream source on the internal feed.

Remove azure artifacts publish step

---

Directory.Packages.props
src/Microsoft.ComponentDetection.Detectors/Microsoft.ComponentDetection.Detectors.csproj

Technically DoS doesn't impact the tool, but still, bumping `System.Formats.Asn1` to address CVE-2024-38095
`NuGet.ProjectModel 6.10.0` is the root dependency that brings the vulnerable package transitively.

Fix security alert

---

docs/detectors/maven.md
docs/environment-variables.md
src/Microsoft.ComponentDetection.Common/DirectoryItemFacadeOptimized.cs
src/Microsoft.ComponentDetection.Contracts/FileComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/go/GoComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/go/GoComponentWithReplaceDetector.cs
src/Microsoft.ComponentDetection.Detectors/ivy/IvyDetector.cs
src/Microsoft.ComponentDetection.Detectors/maven/IMavenCommandService.cs
src/Microsoft.ComponentDetection.Detectors/maven/MavenCommandService.cs
src/Microsoft.ComponentDetection.Detectors/maven/MvnCliComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/npm/NpmLockfileDetectorBase.cs
src/Microsoft.ComponentDetection.Detectors/pip/PipComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/pip/PipReportComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/pip/SimplePipComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/MavenCommandServiceTests.cs

MvnCLI can hang when scanning directories with significant amount of pom.xmls. At the moment it is hard to tell if this is bug in the detector itself or Mvn CLI APIs.
We are adding logs to be able to improve troubleshooting the detector, and we are also introducing a build variable called `MvnCLIFileLevelTimeoutSeconds` that will allow users restrict max time execution per each processed file. Screenshot below on how the logs when the build variable sets a very low threshold, and the tool cancels the command's execution.

Add logs to MvnCLI and use dictionaries to improve perf on large repos

---

src/Microsoft.ComponentDetection.Detectors/pip/PipCommandService.cs
src/Microsoft.ComponentDetection.Detectors/pip/PipReportComponentDetector.cs

The primary use case here is when the same build stage has both Component Detection and SBOM (where CD runs again). This will allow whichever comes second to be able to just use the previous runs' reports, rather than regenerating them.

Add support to persist pip reports

---

docs/detectors/pip.md
src/Microsoft.ComponentDetection.Common/FileUtilityService.cs
src/Microsoft.ComponentDetection.Contracts/FileComponentDetector.cs
src/Microsoft.ComponentDetection.Contracts/IFileUtilityService.cs
src/Microsoft.ComponentDetection.Detectors/pip/PipCommandService.cs
src/Microsoft.ComponentDetection.Detectors/pip/PipReportComponentDetector.cs
test/Microsoft.ComponentDetection.Common.Tests/FileUtilityServiceTests.cs
test/Microsoft.ComponentDetection.Common.Tests/Microsoft.ComponentDetection.Common.Tests.csproj
test/Microsoft.ComponentDetection.Common.Tests/Resources/test-file-duplicate.txt
test/Microsoft.ComponentDetection.Detectors.Tests/PipCommandServiceTests.cs
test/Microsoft.ComponentDetection.VerificationTests/resources/pip/index-removal/requirements.txt

Customers' pipelines are being broken because they are using file level `requirements.txt` index urls. This adds an option to disable those

Fix bug where pipreport used index-urls from requirements.txt

---

Directory.Packages.props
test/Directory.Build.props
test/Microsoft.ComponentDetection.Common.Tests/Microsoft.ComponentDetection.Common.Tests.csproj
test/Microsoft.ComponentDetection.Contracts.Tests/Microsoft.ComponentDetection.Contracts.Tests.csproj
test/Microsoft.ComponentDetection.Detectors.Tests/Microsoft.ComponentDetection.Detectors.Tests.csproj
test/Microsoft.ComponentDetection.Orchestrator.Tests/Microsoft.ComponentDetection.Orchestrator.Tests.csproj

Dotnet pack is failing, since `testhost.dll` is mistakenly in the TestUtilities Nuget package.
```
The assembly 'content\testhost.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.
```
https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-getting-started mentions 
```
If you are creating a test infrastructure project that is intended to be used as a helper by multiple test projects, you should install the MSTest.TestFramework and MSTest.Analyzers packages directly into that project.
```

Fix MSTest Packages for test utilities

---

src/Microsoft.ComponentDetection.Common/FileUtilityService.cs
src/Microsoft.ComponentDetection.Contracts/IFileUtilityService.cs
src/Microsoft.ComponentDetection.Detectors/Microsoft.ComponentDetection.Detectors.csproj
src/Microsoft.ComponentDetection.Detectors/pip/PipCommandService.cs
test/Microsoft.ComponentDetection.Common.Tests/FileUtilityServiceTests.cs
test/Microsoft.ComponentDetection.Common.Tests/Microsoft.ComponentDetection.Common.Tests.csproj
test/Microsoft.ComponentDetection.Common.Tests/Resources/test-file-duplicate.txt
test/Microsoft.ComponentDetection.Detectors.Tests/PipCommandServiceTests.cs

`-i` or `--index-url` can be used: 
https://pip.pypa.io/en/stable/cli/pip_install/#install-index-url

Add additional removal indicator

---

Directory.Packages.props

Address `Microsoft.Extensions.Caching.Memory` High Severity security alert in https://github.com/advisories/GHSA-qj66-m88j-hmgj.

Bump Caching.Memory nupkg to fix Security alerts

---

docs/detectors/nuget.md

Previous limitations was written before new nuget detector was rolled out. This clarifies some of the points and removes the indication that the new detector hasn't rolled out yet.

Update nuget known limitations

---

src/Microsoft.ComponentDetection.Common/DependencyGraph/ComponentRecorder.cs
src/Microsoft.ComponentDetection.Contracts/BcdeModels/ScannedComponent.cs
src/Microsoft.ComponentDetection.Contracts/ConcurrentHashSet.cs
src/Microsoft.ComponentDetection.Contracts/DetectedComponent.cs
src/Microsoft.ComponentDetection.Contracts/IComponentRecorder.cs
src/Microsoft.ComponentDetection.Contracts/TypedComponent/NugetComponent.cs
src/Microsoft.ComponentDetection.Detectors/ivy/IvyDetector.cs
src/Microsoft.ComponentDetection.Detectors/nuget/NuGetPackageReferenceFrameworkAwareDetector.cs
src/Microsoft.ComponentDetection.Detectors/nuget/NuGetPackagesConfigDetector.cs
src/Microsoft.ComponentDetection.Detectors/nuget/NuGetProjectModelProjectCentricComponentDetector.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/GraphTranslation/DefaultGraphTranslationService.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NuGetProjectModelProjectCentricComponentDetectorTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/nuget/NuGetPackageReferenceFrameworkAwareDetectorTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/nuget/NuGetPackagesConfigDetectorTests.cs

We recently introduced an experimental NuGet detector to start capturing NuGet framework libraries in #1285 and correctly flagging them as dev dependencies. In that same PR we also introduced additional metadata called "TargetFrameworks" in the `NugetComponent` class.
The `TargetFramework` does not serve as an identifying property of a NuGet package; rather, it pertains to the runtime in which it is used. This makes it more appropriate to be documented in the `DetectedComponent`, which serves as a higher-level abstraction where relevant consumption metadata is recorded in the graph across detectors and packages. Additionally, the `HashSet` object lacks thread safety, so a thread-safe class called `ConcurrentHashSet` was developed to avoid data quality issues when multiple detectors are …

Report TargetFrameworks as part of DetectedComponent class

---

src/Microsoft.ComponentDetection.Detectors/nuget/NuGetPackageReferenceFrameworkAwareDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/Mocks/TestResources.Designer.cs
test/Microsoft.ComponentDetection.Detectors.Tests/Mocks/TestResources.resx
test/Microsoft.ComponentDetection.Detectors.Tests/Resources/project_assets_packageDownload.json
test/Microsoft.ComponentDetection.Detectors.Tests/nuget/NuGetPackageReferenceFrameworkAwareDetectorTests.cs

Read PackageDownloads from the assets file and record them as top-level development dependencies.

Record NuGet PackageDownloads

---

src/Microsoft.ComponentDetection.Orchestrator/Services/GraphTranslation/DefaultGraphTranslationService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DefaultGraphTranslationServiceTests.cs

A detector does not need to specify location where a component was found. Nevertheless, custom wrapper plugins can report additional locations if desired and that shouldn't be blocked. 
In PR https://github.com/microsoft/component-detection/pull/648 a regression occurred while trying to address an experiments framework bug. We don't want to unsuspectingly record locations for experimental detectors before producing the final graph. We added a check to prevent experiments from overriding the graph, but this was partially incomplete, because we are clearing the file paths at the top of the method.
Use the same flag to verify if the component file paths should be updated and only clear the list when generating final graph.

Fix detector component filepath custom overrides

---

src/Microsoft.ComponentDetection.Detectors/nuget/FrameworkPackages/FrameworkPackages.cs
src/Microsoft.ComponentDetection.Detectors/nuget/FrameworkPackages/FrameworkPackages.net461.cs
src/Microsoft.ComponentDetection.Detectors/nuget/FrameworkPackages/FrameworkPackages.netcoreapp2.0.cs
src/Microsoft.ComponentDetection.Detectors/nuget/FrameworkPackages/FrameworkPackages.netcoreapp2.1.cs

Microsoft.NETCore.App contains only reference assemblies, but it was listed in CVEs, so should be excluded.  The same is true for System.Private.Uri.
I did not include these previously because they weren't part of package overrides list, nor were they found through package comparisons - since conflict resolution doesn't need to do anything with non-implementation packages.  They are important for CG though since they've been used in CVE reports.
.NET 4.6.1 supports .NET Standard and has built in support for it that will win over nuget packages.
In .NET 4.6.1 - .NET 4.7.1 this comes from the Microsoft.NET.Build.Extensions component, after that it's built into the framework itself.
@grvillic

Framework package updates

---

src/Microsoft.ComponentDetection.Orchestrator/Experiments/Models/ExperimentDiff.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Experiments/ExperimentDiffTests.cs

As we were evaluating the .NET experiment for new detector, we noticed a bug in our experimental diffing evaluation. If a new dev dependency is introduced that is not reported in control group, it should still be reported as a dev dependency. As of now, that component only gets added to the `AddedIds` but it never gets flagged as dev dependency.

Fix Experiments evaluation of new dep dependencies

---

src/Microsoft.ComponentDetection.Detectors/nuget/NuGetPackageReferenceFrameworkAwareDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/nuget/NuGetPackageReferenceFrameworkAwareDetectorTests.cs

While we do know that some PackageDownloads are used at runtime and have active alerts against them - the user action to fix those isn't centered around updating the dependency, it's instead about updating the SDK. As such, we feel that treating them as non-development dependencies now may result in user confusion and lot lead to the right result.

Revert to treating PackageDownload as Development Dependency

---

src/Microsoft.ComponentDetection.Detectors/nuget/FrameworkPackages/FrameworkPackages.cs
src/Microsoft.ComponentDetection.Detectors/nuget/NuGetPackageReferenceFrameworkAwareDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/Mocks/TestResources.Designer.cs
test/Microsoft.ComponentDetection.Detectors.Tests/Mocks/TestResources.resx
test/Microsoft.ComponentDetection.Detectors.Tests/Resources/project.assets_1_1_console.json
test/Microsoft.ComponentDetection.Detectors.Tests/Resources/project.assets_1_1_web.json
test/Microsoft.ComponentDetection.Detectors.Tests/Resources/project.assets_2_1_web.json
test/Microsoft.ComponentDetection.Detectors.Tests/nuget/NuGetPackageReferenceFrameworkAwareDetectorTests.cs

These packages aren't removed completely like later frameworks packages are, but the previous detector would drop them.
For framework dependent apps these packages will be removed from the output.
To minimize new alerts in the new detector we'll treat these as dev dependencies similar to other default package references.

Mark packages from .NETCore 1.x and 2.x as dev dependencies

---

src/Microsoft.ComponentDetection.Contracts/ScanRequest.cs
src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs
test/Microsoft.ComponentDetection.Orchestrator.Tests/Services/DetectorProcessingServiceTests.cs
test/Microsoft.ComponentDetection.TestsUtilities/DetectorTestUtilityBuilder.cs

Custom detectors that inherit from `IDetector` can optionally access the `SourceFileRoot` property in the `ScanRequest` class. 
This is useful if a custom detector wants to use placeholders of the reported file paths under certain conditions rather than just the source directory being scanned by the detector.

Optionally propagate source file root to Detector's scan request

---

docs/update-syft.md
src/Microsoft.ComponentDetection.Detectors/linux/Contracts/SyftOutput.cs
src/Microsoft.ComponentDetection.Detectors/linux/LinuxContainerDetector.cs
src/Microsoft.ComponentDetection.Detectors/linux/LinuxScanner.cs

Reverts microsoft/component-detection#1318 , which re-introduces the Syft update

Re-introduce: Update syft image and doc - use docker commands

---

docs/detectors/go.md

Fix links that weren't formatted correctly in the Go detector documentation. Noticed while working on https://github.com/microsoft/component-detection/issues/1333.

Fix broken links in Go detector doc

---

src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmDetectorTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmTestUtilities.cs

This PR modifies the existing NPM component detector to skip components corresponding to VS Code built-in extensions in order to reduce false positives while scanning the VS Code repository.
Example component that should not be flagged: https://github.com/microsoft/vscode/blob/main/extensions/handlebars/package.json

Register VS Code built-in packages as skipped

---

src/Microsoft.ComponentDetection.Detectors/go/Go117ComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/Go117ComponentDetectorTests.cs

The issue with the go detector was that the command 
```csharp
var processExecution = await this.commandLineInvocationService.ExecuteCommandAsync("go", null, null, cancellationToken: default, new List<string> { "version" }.ToArray());
```
Was throwing an exception because it couldn't find go CLI, even when go was installed. Internally the method `ExecuteCommandAsync` uses other method called `CanCommandBeLocatedAsync` but it calls this method without passing the parameters for the execution of `go`. The problem is that when CanCommandBeLocatedAsync was executing `go` without parameters the process was returning 2 and we expect that a successful command execution should returns 0 [see here](https://github.com/microsoft/component-detection/blob/f763e9632f96139c8f50660a566f6dbb1eb852df/src/Mi …

Fixed scan of multiple go files for the Go117 detector

---

docs/detectors/dotnet.md
src/Microsoft.ComponentDetection.Common/CommandLineInvocationService.cs
src/Microsoft.ComponentDetection.Contracts/TypedComponent/ComponentType.cs
src/Microsoft.ComponentDetection.Contracts/TypedComponent/DotNetComponent.cs
src/Microsoft.ComponentDetection.Detectors/dotnet/DotNetComponentDetector.cs
src/Microsoft.ComponentDetection.Detectors/yarn/YarnLockComponentDetector.cs
src/Microsoft.ComponentDetection.Orchestrator/Experiments/DotNetDetectorExperiment.cs
src/Microsoft.ComponentDetection.Orchestrator/Extensions/ServiceCollectionExtensions.cs
test/Microsoft.ComponentDetection.Detectors.Tests/DotNetComponentDetectorTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/Microsoft.ComponentDetection.Detectors.Tests.csproj

The DotNetComponent type is used to report usage of the .NET SDK version
This is important as the .NET SDK will add redistributable content to the project, so using an older version may mean your application contains unserviced copies of the host or runtime. The TargetFramework and project type is reported as well since these influence what content the SDK may reference.
Some remaining work:

Add DotNetComponent

---

src/Microsoft.ComponentDetection.Detectors/dotnet/DotNetComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/DotNetComponentDetectorTests.cs

We weren't handling EXEs correctly - simply missed this case.
When a global.json mentions a version that doesn't exist on the path, the `dotnet --version` command will fail, and the `commandLineInvocationService` will throw InvalidOperationException since it cannot distinguish this failure from a missing command.  Catch this exception and treat it like a failure so we fallback to parsing `global.json`.

Fix dotnet detector for exes / newer version not on path

---

src/Microsoft.ComponentDetection.Common/Telemetry/Records/LinuxScannerSyftTelemetryRecord.cs
src/Microsoft.ComponentDetection.Detectors/linux/LinuxContainerDetector.cs
src/Microsoft.ComponentDetection.Detectors/linux/LinuxScanner.cs
test/Microsoft.ComponentDetection.Detectors.Tests/LinuxScannerTests.cs

Mariner 2.0 images do not contain a specific enough version in its ELF notes. https://github.com/microsoft/azurelinux/pull/10405 fixes it for azure linux 3.0, but the change is unable to be ported to 2.0. The packages we skip here are detected with the release version elsewhere in the image, so we are safe to remove the incomplete duplicates.

Remove incomplete ELF Syft results for Mariner 2.0

---

src/Microsoft.ComponentDetection.Detectors/dotnet/DotNetComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/DotNetComponentDetectorTests.cs

The assets file always included a trailing separator, whereas the output of GetDirectoryName did not.  This was causing rebasing to fail to find a matching replacement path.
Most of this change is just improving some comments.  The fix is to switch from `pathUtilityService.NormalizePath` to `NormalizeDirectory` which also trims trailing separators.

Fix path rebasing on linux

---

src/Microsoft.ComponentDetection.Common/Telemetry/Records/LinuxScannerSyftTelemetryRecord.cs
src/Microsoft.ComponentDetection.Detectors/linux/LinuxScanner.cs
test/Microsoft.ComponentDetection.Detectors.Tests/LinuxScannerTests.cs

We cannot assume that multistage docker builds will pull in the rpm manifests from the mariner images, so Syft needs to just ignore all ELF package notes files for Mariner 2 images (reverting to previous Syft behavior).

Mariner 2.0 Syft Tweak Ignore Logic

---

src/Microsoft.ComponentDetection.Detectors/pnpm/Pnpm9Detector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/PnpmDetectorTests.cs

I noticed that some pnpm dependencies were being incorrectly marked as root dependencies from a v9 lockfile.
After debugging, I realized the problem was that local dependencies referenced with `workspace:`/`link:` do not appear in the `snapshots` section of the lockfile. As a result, when the detector tries to look them up in the `components` dictionary, an exception is thrown and the rest of the file stops being processed. Because of this, the detector was unable to finish building the dependency graph and incorrectly assumed many dependencies were root dependencies because their ancestor information was never populated.
In order to expose this case in the existing unit test for link dependencies, I added another dependency after `SampleLinkDependency`. Prior to this change, the detector …

Fix pnpm 9 link dependency bug in detector

---

src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentUtilities.cs

When attempting to scan projects that use npm workspaces[^1] there will not be a resolved version in `package-lock.json`. Currently we throw a `NullReferenceException` as we attempt to call `ToString` on this `null` object. An example of how this appears in the `package-lock.json` is:
```json
"node_modules/example": {
"resolved": "scripts",
"link": true
}
```
From the npm documentation[^2]:
> `link`: A flag to indicate that this is a symbolic link. If this is present, no other fields are specified, since the link target will also be included in the lockfile.
After this change, we will log that the version is `null`, and continue parsing:
```
[13:51:57 INF] Version string null for component example is invalid or unsupported and a component will not be recorded.
```
[^1]: …

Allow for `null` resolved version in `package-lock.json`

---

src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmDetectorTests.cs
test/Microsoft.ComponentDetection.Detectors.Tests/NpmTestUtilities.cs

`package.json` files seen in the wild have had a string array instead of an object for the `engines` property (example [here](https://github.com/Tjatse/ansi-html/blob/25ffe44357aa8f28d00239af61b74baced7510e4/package.json#L29)).  Because of this, anything that pulls in one of these variant packages will fail to generate components.
While `engines` should be an object, this PR allows for this alternate form to allow detection to continue.
Fixes #1385

don't throw if `engines` property is a string array

---

src/Microsoft.ComponentDetection.Detectors/vcpkg/Contracts/ManifestInfo.cs
src/Microsoft.ComponentDetection.Detectors/vcpkg/VcpkgComponentDetector.cs
test/Microsoft.ComponentDetection.Detectors.Tests/VcpkgComponentDetectorTests.cs

This is an update to the VCPKG detector to enhance file location metadata resolution by checking vcpkg_installed/manifest-info.json or its fallback to accurately parse and assign vcpkg.json locations for dependencies.
Fixes #1408

Updates to the VCPKG detector to use manifest-info.json for resolving vcpkg.json location.

---

.github/workflows/smoke-test.yml

We need to upgrade VM image to a newer/patched version in this agent. This new image also has less preinstalled software which requires us to install whatever we need for the job to run.
Based on our first executions, dotnet is not coming preinstalled and GitHub Actions seems to not have access to that directory when trying to create it.
The custom agent pool is mostly necessary to try to reproduce concurrency bug that once hit caused an outage when running at scale + we need these tests to run faster than what default agents offer, see https://github.com/microsoft/component-detection/pull/543 for more context.

Update smoke test workflow to install all requirements manually on new vanilla ubuntu image
